#!/usr/bin/env python3
"""
Seed Commonwealth (CTH) and NSW Legislation into PACT Hub's Structured Legislation API.

This ingests real Commonwealth and New South Wales statutes with canonical section IDs,
content summaries, cross-references, and amendment status.

Usage:
    python scripts/seed_cth_nsw_legislation.py [--base-url URL] [--admin-key KEY]

Defaults:
    --base-url https://pacthub.ai
    --admin-key (reads from ADMIN_SECRET env var)
"""

import requests
import os
import sys
import argparse
import json

# ── Configuration ──────────────────────────────────────────────────
DEFAULT_BASE = "https://pacthub.ai"

# ── Commonwealth & NSW Legislation Data ──────────────────────────
# Each document has real section numbers from legislation.gov.au / legislation.nsw.gov.au
# Content is summarized for agent consumption (not full gazette text)

CTH_NSW_ACTS = [
    # ═══════════════════════════════════════════════════════════════
    # COMMONWEALTH (CTH) LEGISLATION
    # ═══════════════════════════════════════════════════════════════
    {
        "id": "cth/act-2011-137",
        "jurisdiction": "CTH",
        "type": "act",
        "title": "Work Health and Safety Act 2011 (Cth)",
        "shortTitle": "WHS Act 2011 (Cth)",
        "year": 2011,
        "number": "Act No. 137 of 2011",
        "inForceDate": "2012-01-01",
        "lastAmendedDate": "2024-07-01",
        "administeredBy": "Safe Work Australia / Comcare",
        "legislationUrl": "https://www.legislation.gov.au/C2011A00137/latest/text",
        "relatedDocs": ["qld/act-2011-018", "nsw/act-2011-010"],
        "sections": [
            {
                "sectionId": "s 3",
                "title": "Object",
                "content": "The main object of this Act is to provide for a balanced and nationally consistent framework to secure the health and safety of workers and workplaces by — (a) protecting workers and other persons against harm to their health, safety and welfare through the elimination or minimisation of risks arising from work or from specified types of substances or plant; and (b) providing for fair and effective workplace representation, consultation, cooperation and issue resolution in relation to work health and safety; and (c) encouraging unions and employer organisations to take a constructive role in promoting improvements in work health and safety practices; and (d) promoting the provision of advice, information, education and training in relation to work health and safety; and (e) securing compliance with this Act through effective and appropriate compliance and enforcement measures.",
                "depth": 1,
                "order": 0,
                "status": "in_force",
            },
            {
                "sectionId": "s 19",
                "title": "Primary duty of care",
                "content": "A person conducting a business or undertaking (PCBU) must ensure, so far as is reasonably practicable, the health and safety of — (a) workers engaged, or caused to be engaged, by the person; and (b) workers whose activities in carrying out work are influenced or directed by the person; while the workers are at work in the business or undertaking. This duty extends to ensuring the provision and maintenance of a work environment without risks to health and safety, safe plant and structures, safe systems of work, safe use, handling and storage of plant, structures and substances, adequate facilities for the welfare of workers, and any information, training, instruction or supervision necessary to protect all persons from risks to their health and safety. A PCBU must also ensure, so far as is reasonably practicable, that the health and safety of other persons is not put at risk from work carried out as part of the conduct of the business or undertaking. Maximum penalty — (a) for an individual — $300,000; (b) for a body corporate — $3,000,000.",
                "depth": 2,
                "order": 1,
                "parentSection": "Part 2 — Health and Safety Duties",
                "status": "in_force",
                "crossReferences": ["s 17 (management of risks)", "s 27", "s 28"],
            },
            {
                "sectionId": "s 27",
                "title": "Duty of officers",
                "content": "If a person conducting a business or undertaking has a duty or obligation under this Act, an officer of the person must exercise due diligence to ensure that the person complies with that duty or obligation. Due diligence includes — (a) acquiring and keeping up-to-date knowledge of work health and safety matters; (b) gaining an understanding of the nature of the operations of the business or undertaking and generally of the hazards and risks associated with those operations; (c) ensuring that the person conducting the business or undertaking has available for use, and uses, appropriate resources and processes to eliminate or minimise risks to health and safety from work carried out as part of the conduct of the business or undertaking; (d) ensuring that the person has appropriate processes for receiving and considering information regarding incidents, hazards and risks and responding in a timely way to that information; (e) ensuring that the person has, and implements, processes for complying with any duty or obligation of the person under this Act; (f) verifying the provision and use of the resources and processes referred to above. Maximum penalty — $600,000 (if PCBU or officer) or 5 years imprisonment.",
                "depth": 2,
                "order": 2,
                "parentSection": "Part 2 — Health and Safety Duties",
                "status": "in_force",
                "crossReferences": ["s 19", "s 28", "Corporations Act 2001 s 180"],
            },
            {
                "sectionId": "s 28",
                "title": "Duties of workers",
                "content": "While at work, a worker must — (a) take reasonable care for his or her own health and safety; and (b) take reasonable care that his or her acts or omissions do not adversely affect the health and safety of other persons; and (c) comply, so far as the worker is reasonably able, with any reasonable instruction that is given by the person conducting the business or undertaking to allow the person to comply with this Act; and (d) cooperate with any reasonable policy or procedure of the person conducting the business or undertaking relating to health or safety at the workplace that has been notified to workers. Maximum penalty — $50,000.",
                "depth": 2,
                "order": 3,
                "parentSection": "Part 2 — Health and Safety Duties",
                "status": "in_force",
                "crossReferences": ["s 19", "s 27"],
            },
            {
                "sectionId": "s 31",
                "title": "Category 1 — Reckless conduct — category 1",
                "content": "A person commits a category 1 offence if — (a) the person has a health and safety duty; and (b) the person, without reasonable excuse, engages in conduct that exposes an individual to whom that duty is owed to a risk of death or serious injury or illness; and (c) the person is reckless as to the risk to an individual of death or serious injury or illness. Maximum penalty — (a) for an individual as a PCBU or an officer of a PCBU — $600,000 or 5 years imprisonment; (b) for any other individual — $300,000; (c) for a body corporate — $3,000,000.",
                "depth": 2,
                "order": 4,
                "parentSection": "Part 2 — Division 5 — Offences and Penalties",
                "status": "in_force",
                "crossReferences": ["s 32", "s 33"],
            },
            {
                "sectionId": "s 32",
                "title": "Category 2 — Failure to comply with health and safety duty — category 2",
                "content": "A person commits a category 2 offence if — (a) the person has a health and safety duty; and (b) the person fails to comply with that duty; and (c) the failure exposes an individual to a risk of death or serious injury or illness. The prosecution is not required to prove that the person intended to expose an individual to such risk. Maximum penalty — (a) for an individual as a PCBU or an officer — $300,000; (b) for any other individual — $150,000; (c) for a body corporate — $1,500,000.",
                "depth": 2,
                "order": 5,
                "parentSection": "Part 2 — Division 5 — Offences and Penalties",
                "status": "in_force",
                "crossReferences": ["s 31", "s 33"],
            },
            {
                "sectionId": "s 33",
                "title": "Category 3 — Failure to comply with health and safety duty — category 3",
                "content": "A person commits a category 3 offence if — (a) the person has a health and safety duty; and (b) the person fails to comply with that duty. This category does not require exposure to risk of death or serious injury. Maximum penalty — (a) for an individual as a PCBU or an officer — $100,000; (b) for any other individual — $50,000; (c) for a body corporate — $500,000.",
                "depth": 2,
                "order": 6,
                "parentSection": "Part 2 — Division 5 — Offences and Penalties",
                "status": "in_force",
                "crossReferences": ["s 31", "s 32"],
            },
            {
                "sectionId": "s 47",
                "title": "Duty to consult with workers",
                "content": "A person conducting a business or undertaking must, so far as is reasonably practicable, consult with workers who carry out work for the business or undertaking and who are, or are likely to be, directly affected by a matter relating to work health or safety. Consultation must involve sharing information about the matter with workers, giving workers a reasonable opportunity to express their views, and taking those views into account. If workers are represented by a health and safety representative, the consultation must involve that representative.",
                "depth": 2,
                "order": 7,
                "parentSection": "Part 5 — Consultation, Representation and Participation",
                "status": "in_force",
                "crossReferences": ["s 48 (nature of consultation)", "s 49 (when consultation is required)"],
            },
            {
                "sectionId": "s 79",
                "title": "Issue resolution",
                "content": "The parties to a work health and safety issue must make reasonable efforts to achieve a timely, final and effective resolution of the issue in accordance with the relevant agreed procedure, or if there is no agreed procedure, the default procedure set out in the regulations. If the issue remains unresolved, any party may ask the regulator to appoint an inspector to assist in resolving the issue. A health and safety representative for a work group that includes a worker who is a party to the issue may, after following the issue resolution procedure, direct that unsafe work cease if the representative has a reasonable concern that carrying out the work would expose workers to a serious risk.",
                "depth": 2,
                "order": 8,
                "parentSection": "Part 5 — Division 5 — Issue Resolution",
                "status": "in_force",
                "crossReferences": ["s 47", "s 74 (health and safety representatives)"],
            },
        ],
    },
    {
        "id": "cth/act-1988-119",
        "jurisdiction": "CTH",
        "type": "act",
        "title": "Privacy Act 1988 (Cth)",
        "shortTitle": "Privacy Act 1988",
        "year": 1988,
        "number": "Act No. 119 of 1988",
        "inForceDate": "1989-01-01",
        "lastAmendedDate": "2024-12-01",
        "administeredBy": "Office of the Australian Information Commissioner",
        "legislationUrl": "https://www.legislation.gov.au/C2004A03712/latest/text",
        "relatedDocs": ["qld/act-2009-014"],
        "sections": [
            {
                "sectionId": "s 6",
                "title": "Interpretation — Definitions",
                "content": "This section provides core definitions used throughout the Act. 'Personal information' means information or an opinion about an identified individual, or an individual who is reasonably identifiable, whether the information or opinion is true or not and whether recorded in a material form or not. 'Sensitive information' means information or an opinion about an individual's racial or ethnic origin, political opinions, religious beliefs, sexual orientation, criminal record, health information, genetic information, biometric information or trade union membership. 'APP entity' means an agency or organisation that is subject to the Australian Privacy Principles. 'Australian Privacy Principle' or 'APP' means an Australian Privacy Principle set out in Schedule 1.",
                "depth": 1,
                "order": 0,
                "status": "in_force",
            },
            {
                "sectionId": "APP 1",
                "title": "Open and transparent management of personal information",
                "content": "An APP entity must take such steps as are reasonable in the circumstances to implement practices, procedures and systems relating to the entity's functions or activities that will ensure compliance with the APPs and any binding registered APP code. An APP entity must have a clearly expressed and up-to-date privacy policy about the management of personal information by the entity, including the kinds of personal information collected, how it is collected and held, the purposes for which it is collected, how an individual may access and correct their information, how complaints are dealt with, and whether information is disclosed overseas.",
                "depth": 3,
                "order": 1,
                "parentSection": "Schedule 1 — Australian Privacy Principles",
                "status": "in_force",
            },
            {
                "sectionId": "APP 3",
                "title": "Collection of solicited personal information",
                "content": "An APP entity must not collect personal information (other than sensitive information) unless the information is reasonably necessary for, or directly related to, one or more of the entity's functions or activities. An entity must not collect sensitive information about an individual unless the individual consents to the collection and the information is reasonably necessary for one or more of the entity's functions, or the collection is required or authorised by or under an Australian law or a court/tribunal order. Personal information must be collected only by lawful and fair means, and must be collected directly from the individual unless it is unreasonable or impracticable to do so.",
                "depth": 3,
                "order": 2,
                "parentSection": "Schedule 1 — Australian Privacy Principles",
                "status": "in_force",
                "crossReferences": ["APP 1", "APP 6"],
            },
            {
                "sectionId": "APP 6",
                "title": "Use or disclosure of personal information",
                "content": "If an APP entity holds personal information about an individual that was collected for a particular purpose (the primary purpose), the entity must not use or disclose the information for another purpose (the secondary purpose) unless — (a) the individual has consented; (b) the individual would reasonably expect the entity to use or disclose the information for the secondary purpose, and that purpose is related to the primary purpose (or, for sensitive information, directly related); (c) the use or disclosure is required or authorised by or under an Australian law or a court/tribunal order; (d) a permitted general situation exists (e.g., to lessen or prevent a serious threat to life, health or safety); or (e) the entity reasonably believes the use or disclosure is necessary for enforcement related activities conducted by an enforcement body.",
                "depth": 3,
                "order": 3,
                "parentSection": "Schedule 1 — Australian Privacy Principles",
                "status": "in_force",
                "crossReferences": ["APP 3", "APP 11"],
            },
            {
                "sectionId": "APP 11",
                "title": "Security of personal information",
                "content": "An APP entity must take such steps as are reasonable in the circumstances to protect personal information it holds from misuse, interference and loss, and from unauthorised access, modification or disclosure. If an APP entity holds personal information about an individual and the entity no longer needs the information for any purpose for which the information may be used or disclosed under the APPs, the entity is not required by or under an Australian law or court/tribunal order to retain the information, and the information is not contained in a Commonwealth record, the entity must take such steps as are reasonable in the circumstances to destroy the information or to ensure that the information is de-identified.",
                "depth": 3,
                "order": 4,
                "parentSection": "Schedule 1 — Australian Privacy Principles",
                "status": "in_force",
                "crossReferences": ["APP 6", "s 26WH (notifiable data breaches)"],
            },
            {
                "sectionId": "APP 12",
                "title": "Access to personal information",
                "content": "If an APP entity holds personal information about an individual, the entity must, on request by the individual, give the individual access to the information. The entity must respond to the request within 30 days. An entity may refuse to give access if the entity reasonably believes that giving access would pose a serious threat to the life, health or safety of any individual or to public health or safety, giving access would have an unreasonable impact on the privacy of other individuals, the request is frivolous or vexatious, or giving access would be unlawful or would prejudice enforcement activities.",
                "depth": 3,
                "order": 5,
                "parentSection": "Schedule 1 — Australian Privacy Principles",
                "status": "in_force",
                "crossReferences": ["APP 13"],
            },
            {
                "sectionId": "APP 13",
                "title": "Correction of personal information",
                "content": "If an APP entity holds personal information about an individual, and either the entity is satisfied that, having regard to a purpose for which the information is held, the information is inaccurate, out of date, incomplete, irrelevant or misleading, or the individual requests the entity to correct the information, the entity must take such steps as are reasonable in the circumstances to correct the information. The entity must respond to a correction request within 30 days. If the entity refuses to correct the information, it must give the individual a written notice explaining the refusal and how to complain.",
                "depth": 3,
                "order": 6,
                "parentSection": "Schedule 1 — Australian Privacy Principles",
                "status": "in_force",
                "crossReferences": ["APP 12"],
            },
            {
                "sectionId": "s 26WH",
                "title": "Notification of eligible data breaches",
                "content": "If an APP entity has reasonable grounds to believe that an eligible data breach has occurred, the entity must, as soon as practicable, prepare a statement that includes the identity and contact details of the entity, a description of the data breach, the kinds of information concerned, and recommendations about the steps individuals should take in response to the breach. The entity must give a copy of the statement to the Information Commissioner and must take reasonable steps to notify each individual whose personal information is involved in the eligible data breach. An 'eligible data breach' occurs where there is unauthorised access to, or unauthorised disclosure of, personal information held by an entity, or information is lost in circumstances where unauthorised access or disclosure is likely to occur, and a reasonable person would conclude that the breach would be likely to result in serious harm to the affected individuals.",
                "depth": 2,
                "order": 7,
                "parentSection": "Part IIIC — Notifiable Data Breaches",
                "status": "in_force",
                "crossReferences": ["APP 11", "APP 1"],
                "notes": "The Notifiable Data Breaches scheme commenced 22 February 2018. Failure to comply may result in civil penalties up to $50,000,000 for a body corporate.",
            },
        ],
    },
    {
        "id": "cth/act-2009-028",
        "jurisdiction": "CTH",
        "type": "act",
        "title": "Fair Work Act 2009 (Cth)",
        "shortTitle": "Fair Work Act 2009",
        "year": 2009,
        "number": "Act No. 28 of 2009",
        "inForceDate": "2009-07-01",
        "lastAmendedDate": "2024-12-01",
        "administeredBy": "Fair Work Commission / Fair Work Ombudsman",
        "legislationUrl": "https://www.legislation.gov.au/C2009A00028/latest/text",
        "sections": [
            {
                "sectionId": "s 3",
                "title": "Object of this Act",
                "content": "The object of this Act is to provide a balanced framework for cooperative and productive workplace relations that promotes national economic prosperity and social inclusion for all Australians by — (a) providing workplace relations laws that are fair to working Australians, are flexible for businesses, promote productivity and economic growth for Australia's future economic prosperity, and take into account Australia's international labour obligations; and (b) ensuring a guaranteed safety net of fair, relevant and enforceable minimum terms and conditions through the National Employment Standards, modern awards and national minimum wage orders; and (c) ensuring that the guaranteed safety net of fair, relevant and enforceable minimum wages and conditions can no longer be undermined by the making of statutory individual employment agreements; and (d) assisting employees to balance their work and family responsibilities through flexible working arrangements; and (e) enabling fairness and representation at work and the prevention of discrimination by recognising the right to freedom of association and the right to be represented, protecting against unfair treatment and discrimination, providing accessible and effective procedures to resolve grievances and disputes.",
                "depth": 1,
                "order": 0,
                "status": "in_force",
            },
            {
                "sectionId": "s 44",
                "title": "The National Employment Standards",
                "content": "The National Employment Standards (NES) are minimum employment entitlements that apply to all employees covered by the national workplace relations system. The NES comprise the following — (a) maximum weekly hours of work (Division 3); (b) requests for flexible working arrangements (Division 4); (c) offers and requests to convert from casual employment (Division 4A); (d) parental leave and related entitlements (Division 5); (e) annual leave (Division 6); (f) personal/carer's leave, compassionate leave and family and domestic violence leave (Division 7); (g) community service leave (Division 8); (h) long service leave (Division 9); (i) public holidays (Division 10); (j) notice of termination and redundancy pay (Division 11); (k) provision of a Fair Work Information Statement and a Casual Employment Information Statement (Division 12); (l) superannuation (Division 13).",
                "depth": 2,
                "order": 1,
                "parentSection": "Part 2-2 — The National Employment Standards",
                "status": "in_force",
                "crossReferences": ["s 61", "s 87", "s 117"],
            },
            {
                "sectionId": "s 61",
                "title": "Maximum weekly hours",
                "content": "An employer must not request or require an employee to work more than 38 hours in a week (or, for employees who are not full-time, the lesser of 38 hours or the employee's ordinary hours of work in a week) unless the additional hours are reasonable. In determining whether additional hours are reasonable, the following must be taken into account — (a) any risk to employee health and safety; (b) the employee's personal circumstances including family responsibilities; (c) the needs of the workplace or enterprise; (d) whether the employee is entitled to receive overtime payments, penalty rates or other compensation for working the additional hours; (e) any notice given by the employer of any request or requirement to work the additional hours; (f) any notice given by the employee of the employee's intention to refuse to work the additional hours; (g) the usual patterns of work in the industry; (h) the nature of the employee's role and the employee's level of responsibility; (i) whether the additional hours are in accordance with averaging terms.",
                "depth": 2,
                "order": 2,
                "parentSection": "Part 2-2 — Division 3 — Maximum Weekly Hours",
                "status": "in_force",
                "crossReferences": ["s 44", "s 62 (employee may refuse)"],
            },
            {
                "sectionId": "s 87",
                "title": "Entitlement to annual leave",
                "content": "An employee (other than a casual employee) is entitled to 4 weeks of paid annual leave for each year of service with an employer. A shift worker is entitled to 5 weeks of paid annual leave for each year of service. Annual leave accrues progressively during a year of service according to the employee's ordinary hours of work, and accumulates from year to year. Annual leave is to be paid at the employee's base rate of pay for the employee's ordinary hours of work in the period. An employee may, by agreement with the employer, cash out a period of paid annual leave, provided the employee retains at least 4 weeks' accrued leave after the cashing out.",
                "depth": 2,
                "order": 3,
                "parentSection": "Part 2-2 — Division 6 — Annual Leave",
                "status": "in_force",
                "crossReferences": ["s 44", "s 90 (taking of annual leave)"],
            },
            {
                "sectionId": "s 117",
                "title": "Requirement for notice of termination or payment in lieu",
                "content": "An employer must not terminate an employee's employment unless the employer has given the employee written notice of the day of termination (which cannot be before the day the notice is given). The minimum period of notice is — (a) 1 week if the employee's period of continuous service is not more than 1 year; (b) 2 weeks if the employee's period of continuous service is more than 1 year but not more than 3 years; (c) 3 weeks if the employee's period of continuous service is more than 3 years but not more than 5 years; (d) 4 weeks if the employee's period of continuous service is more than 5 years. The period of notice is increased by 1 week if the employee is over 45 years old and has completed at least 2 years of continuous service. An employer may pay the employee in lieu of the notice period.",
                "depth": 2,
                "order": 4,
                "parentSection": "Part 2-2 — Division 11 — Notice of Termination and Redundancy Pay",
                "status": "in_force",
                "crossReferences": ["s 44", "s 119 (redundancy pay)", "s 385"],
            },
            {
                "sectionId": "s 385",
                "title": "What is an unfair dismissal",
                "content": "A person has been unfairly dismissed if the Fair Work Commission is satisfied that — (a) the person has been dismissed; and (b) the dismissal was harsh, unjust or unreasonable; and (c) the dismissal was not consistent with the Small Business Fair Dismissal Code (if it applies); and (d) the dismissal was not a case of genuine redundancy. A person is only protected from unfair dismissal if — the person is an employee who has completed the minimum employment period (6 months, or 12 months for small business employers); and the person's annual rate of earnings is less than the high income threshold (indexed annually), or a modern award or enterprise agreement covers the person.",
                "depth": 2,
                "order": 5,
                "parentSection": "Part 3-2 — Unfair Dismissal",
                "status": "in_force",
                "crossReferences": ["s 387", "s 396"],
            },
            {
                "sectionId": "s 387",
                "title": "Criteria for considering harshness etc.",
                "content": "In considering whether a dismissal was harsh, unjust or unreasonable, the Fair Work Commission must take into account — (a) whether there was a valid reason for the dismissal related to the person's capacity or conduct (including its effect on the safety and welfare of other employees); (b) whether the person was notified of that reason; (c) whether the person was given an opportunity to respond to any reason related to the capacity or conduct of the person; (d) any unreasonable refusal by the employer to allow the person to have a support person present to assist at any discussions relating to the dismissal; (e) if the dismissal related to unsatisfactory performance by the person — whether the person had been warned about that unsatisfactory performance before the dismissal; (f) the degree to which the size of the employer's enterprise would be likely to impact on the procedures followed in effecting the dismissal; (g) the degree to which the absence of dedicated human resource management specialists or expertise in the enterprise would be likely to impact on the procedures followed; (h) any other matters that the FWC considers relevant.",
                "depth": 2,
                "order": 6,
                "parentSection": "Part 3-2 — Unfair Dismissal",
                "status": "in_force",
                "crossReferences": ["s 385", "s 396"],
            },
            {
                "sectionId": "s 396",
                "title": "Initial matters to be considered before merits",
                "content": "The Fair Work Commission must decide the following matters relating to an application for an unfair dismissal remedy before considering the merits of the application — (a) whether the application was made within the period required (21 days after dismissal took effect, subject to extension); (b) whether the person was protected from unfair dismissal; (c) whether the dismissal was consistent with the Small Business Fair Dismissal Code (if applicable); (d) whether the dismissal was a case of genuine redundancy.",
                "depth": 2,
                "order": 7,
                "parentSection": "Part 3-2 — Unfair Dismissal",
                "status": "in_force",
                "crossReferences": ["s 385", "s 387", "s 394 (application for remedy)"],
            },
            {
                "sectionId": "s 789FD",
                "title": "When the FWC may make an order to stop bullying",
                "content": "If a worker has made an application under section 789FC and the FWC is satisfied that — (a) the worker has been bullied at work; and (b) there is a risk that the worker will continue to be bullied at work; the FWC may make any order it considers appropriate (other than an order requiring payment of a pecuniary amount) to prevent the worker from being bullied at work. A worker is 'bullied at work' if, while the worker is at work in a constitutionally-covered business, an individual or group of individuals repeatedly behaves unreasonably towards the worker or a group of workers of which the worker is a member, and that behaviour creates a risk to health and safety. Bullying at work does not include reasonable management action carried out in a reasonable manner.",
                "depth": 2,
                "order": 8,
                "parentSection": "Part 6-4B — Workers Bullied at Work",
                "status": "in_force",
                "crossReferences": ["s 789FC (application)", "s 789FF (FWC orders)"],
            },
        ],
    },
    {
        "id": "cth/act-2010-109",
        "jurisdiction": "CTH",
        "type": "act",
        "title": "Competition and Consumer Act 2010 (Cth)",
        "shortTitle": "CCA 2010",
        "year": 2010,
        "number": "Act No. 109 of 2010",
        "inForceDate": "2011-01-01",
        "lastAmendedDate": "2024-11-01",
        "administeredBy": "Australian Competition and Consumer Commission (ACCC)",
        "legislationUrl": "https://www.legislation.gov.au/C2004A00109/latest/text",
        "sections": [
            {
                "sectionId": "s 18",
                "title": "Misleading or deceptive conduct",
                "content": "A person must not, in trade or commerce, engage in conduct that is misleading or deceptive or is likely to mislead or deceive. This is a broad prohibition that does not require intention to mislead. Conduct includes representations, omissions, and silence where there is an obligation to speak. Remedies include injunctions, damages, and other orders under the Australian Consumer Law (Schedule 2). This section applies to corporations under the Competition and Consumer Act, with equivalent provisions in Schedule 2 (Australian Consumer Law) applying to individuals and unincorporated entities through state and territory application legislation.",
                "depth": 2,
                "order": 0,
                "parentSection": "Schedule 2 — Australian Consumer Law, Chapter 2 — General Protections",
                "status": "in_force",
                "crossReferences": ["s 29", "Schedule 2 (Australian Consumer Law)"],
                "notes": "This is one of the most frequently litigated provisions in Australian commercial law. It applies to pre-contractual dealings, advertising, and ongoing commercial conduct.",
            },
            {
                "sectionId": "s 29",
                "title": "False or misleading representations about goods or services",
                "content": "A person must not, in trade or commerce, in connection with the supply or possible supply of goods or services or in connection with the promotion of the supply or use of goods or services, make a false or misleading representation — (a) that goods are of a particular standard, quality, value, grade, composition, style, or model, or have had a particular history or particular previous use; (b) that services are of a particular standard, quality, value or grade; (c) that goods are new; (d) that a particular person has agreed to acquire the goods or services; (e) that goods or services have sponsorship, approval, performance characteristics, accessories, uses or benefits they do not have; (f) that the person has a sponsorship, approval or affiliation they do not have; (g) concerning the price of goods or services; (h) concerning the availability of facilities for repair of goods or spare parts; (i) concerning the place of origin of goods; (j) concerning the need for any goods or services; (k) concerning the existence, exclusion or effect of any condition, warranty, guarantee, right or remedy. Maximum civil pecuniary penalty — $10,000,000 for an individual; $50,000,000 for a body corporate (or 3 times the benefit obtained or 30% of turnover, whichever is greater).",
                "depth": 2,
                "order": 1,
                "parentSection": "Schedule 2 — Australian Consumer Law, Chapter 3 — Specific Protections",
                "status": "in_force",
                "crossReferences": ["s 18"],
            },
            {
                "sectionId": "s 46",
                "title": "Misuse of market power",
                "content": "A corporation that has a substantial degree of power in a market must not engage in conduct that has the purpose, or has or is likely to have the effect, of substantially lessening competition in that market or any other market in which the corporation, a body corporate that is related to the corporation, or any of those corporations, supplies or acquires goods or services. In determining whether a corporation has a substantial degree of market power, the court may have regard to the extent to which the conduct of the corporation is constrained by competitors and potential competitors, the extent to which it is constrained by the countervailing power of suppliers or acquirers, and the likelihood that the corporation could increase prices or reduce quality profitably. Maximum penalty — $10,000,000 for an individual; the greater of $50,000,000, 3 times the benefit obtained, or 30% of annual turnover for a body corporate.",
                "depth": 2,
                "order": 2,
                "parentSection": "Part IV — Restrictive Trade Practices",
                "status": "in_force",
                "crossReferences": ["s 47", "s 50"],
                "notes": "Section 46 was substantially amended by the Competition and Consumer Amendment (Misuse of Market Power) Act 2017, replacing the 'take advantage' test with an 'effects' test.",
            },
            {
                "sectionId": "s 47",
                "title": "Exclusive dealing",
                "content": "A corporation must not engage in exclusive dealing conduct that has the purpose, or has or is likely to have the effect, of substantially lessening competition. Exclusive dealing occurs when a corporation supplies goods or services on the condition that the acquirer will not acquire goods or services from a competitor, or when a corporation refuses to supply goods or services because the acquirer has acquired goods or services from a competitor (third line forcing). Maximum penalty — $10,000,000 for an individual; the greater of $50,000,000, 3 times the benefit obtained, or 30% of annual turnover for a body corporate.",
                "depth": 2,
                "order": 3,
                "parentSection": "Part IV — Restrictive Trade Practices",
                "status": "in_force",
                "crossReferences": ["s 46", "s 50"],
                "notes": "Third line forcing was previously a per se contravention but since the Competition and Consumer Amendment (Competition Policy Review) Act 2017, all exclusive dealing is subject to the substantial lessening of competition test.",
            },
            {
                "sectionId": "s 50",
                "title": "Prohibition of acquisitions that substantially lessen competition",
                "content": "A corporation must not directly or indirectly acquire shares in the capital of a body corporate, or acquire any assets of a person, if the acquisition would have the effect, or be likely to have the effect, of substantially lessening competition in any market. In determining whether the acquisition would be likely to substantially lessen competition, the following factors must be considered — (a) the actual and potential level of import competition; (b) the height of barriers to entry to the market; (c) the level of concentration in the market; (d) the degree of countervailing power in the market; (e) the likelihood that the acquisition would result in the acquirer being able to significantly and sustainably increase prices or profit margins; (f) the extent to which substitutes are available in the market; (g) the dynamic characteristics of the market including growth, innovation and product differentiation; (h) the likelihood of removal from the market of a vigorous and effective competitor; (i) the nature and extent of vertical integration in the market.",
                "depth": 2,
                "order": 4,
                "parentSection": "Part IV — Restrictive Trade Practices",
                "status": "in_force",
                "crossReferences": ["s 50A (mergers authorisation)", "s 46"],
            },
            {
                "sectionId": "s 21",
                "title": "Unconscionable conduct in connection with goods or services",
                "content": "A person must not, in trade or commerce, in connection with the supply or possible supply of goods or services to a person, engage in conduct that is, in all the circumstances, unconscionable. Without limiting the matters to which the court may have regard for the purpose of determining whether a person has contravened this section, the court may have regard to — (a) the relative strengths of the bargaining positions of the parties; (b) whether, as a result of conduct engaged in by the person, the consumer was required to comply with conditions that were not reasonably necessary; (c) whether the consumer was able to understand any documents relating to the supply; (d) whether any undue influence or pressure was exerted on, or any unfair tactics were used against, the consumer; (e) the amount for which, and the circumstances under which, the consumer could have acquired identical or equivalent goods or services from another supplier. Maximum civil pecuniary penalty — $10,000,000 for an individual; $50,000,000 for a body corporate.",
                "depth": 2,
                "order": 5,
                "parentSection": "Schedule 2 — Australian Consumer Law, Chapter 2 — General Protections",
                "status": "in_force",
                "crossReferences": ["s 18"],
            },
            {
                "sectionId": "Schedule 2",
                "title": "Australian Consumer Law",
                "content": "Schedule 2 of the Competition and Consumer Act 2010 contains the Australian Consumer Law (ACL), which is a national law that applies uniformly across all Australian states and territories. The ACL provides consumer protections including — (a) general protections against misleading or deceptive conduct and unconscionable conduct; (b) specific protections against unfair practices including false representations, unsolicited supplies, pyramid schemes, and component pricing; (c) unfair contract terms provisions for standard form consumer and small business contracts; (d) consumer guarantees that goods and services meet certain standards (including acceptable quality, fitness for purpose, correspondence with description, and due care and skill); (e) product safety provisions; and (f) enforcement and remedies provisions including civil pecuniary penalties, injunctions, damages, compensation orders, and non-party consumer redress. The ACL applies to all persons in trade or commerce, including corporations and individuals.",
                "depth": 1,
                "order": 6,
                "status": "in_force",
                "crossReferences": ["s 18", "s 29", "s 21"],
            },
        ],
    },
    {
        "id": "cth/act-2001-050",
        "jurisdiction": "CTH",
        "type": "act",
        "title": "Corporations Act 2001 (Cth)",
        "shortTitle": "Corporations Act 2001",
        "year": 2001,
        "number": "Act No. 50 of 2001",
        "inForceDate": "2001-07-15",
        "lastAmendedDate": "2024-12-01",
        "administeredBy": "Australian Securities and Investments Commission (ASIC)",
        "legislationUrl": "https://www.legislation.gov.au/C2004A00818/latest/text",
        "sections": [
            {
                "sectionId": "s 180",
                "title": "Care and diligence — civil obligation only",
                "content": "A director or other officer of a corporation must exercise their powers and discharge their duties with the degree of care and diligence that a reasonable person would exercise if they — (a) were a director or officer of a corporation in the corporation's circumstances; and (b) occupied the office held by, and had the same responsibilities within the corporation as, the director or officer. The business judgment rule provides that a director or other officer who makes a business judgment is taken to meet the requirements of this section if they — (a) make the judgment in good faith for a proper purpose; (b) do not have a material personal interest in the subject matter of the judgment; (c) inform themselves about the subject matter of the judgment to the extent they reasonably believe to be appropriate; and (d) rationally believe that the judgment is in the best interests of the corporation.",
                "depth": 2,
                "order": 0,
                "parentSection": "Part 2D.1 — Duties and Powers of Directors",
                "status": "in_force",
                "crossReferences": ["s 181", "s 182", "s 183", "cth/act-2011-137 s 27 (WHS officer duty)"],
            },
            {
                "sectionId": "s 181",
                "title": "Good faith — civil obligation only",
                "content": "A director or other officer of a corporation must exercise their powers and discharge their duties — (a) in good faith in the best interests of the corporation; and (b) for a proper purpose. A person who is involved in a contravention of this section contravenes this section. This is a civil penalty provision and may also give rise to a compensation order under section 1317H.",
                "depth": 2,
                "order": 1,
                "parentSection": "Part 2D.1 — Duties and Powers of Directors",
                "status": "in_force",
                "crossReferences": ["s 180", "s 182", "s 183"],
            },
            {
                "sectionId": "s 182",
                "title": "Use of position — civil obligations",
                "content": "A director, secretary, other officer or employee of a corporation must not improperly use their position to — (a) gain an advantage for themselves or someone else; or (b) cause detriment to the corporation. A person who is involved in a contravention of this section contravenes this section. This section applies in addition to the general law duty of loyalty. Contravention may give rise to civil penalties under section 1317E (maximum penalty of $1,110,000 for an individual), criminal liability under section 184 (maximum penalty of $357,000 or 5 years imprisonment), or compensation orders under section 1317H.",
                "depth": 2,
                "order": 2,
                "parentSection": "Part 2D.1 — Duties and Powers of Directors",
                "status": "in_force",
                "crossReferences": ["s 180", "s 181", "s 183", "s 184 (criminal offences)"],
            },
            {
                "sectionId": "s 183",
                "title": "Use of information — civil obligations",
                "content": "A person who obtains information because they are, or have been, a director or other officer or employee of a corporation must not improperly use the information to — (a) gain an advantage for themselves or someone else; or (b) cause detriment to the corporation. This duty continues to apply after the person ceases to be a director, officer or employee. A person who is involved in a contravention of this section contravenes this section. This is a civil penalty provision and the criminal equivalent is in section 184.",
                "depth": 2,
                "order": 3,
                "parentSection": "Part 2D.1 — Duties and Powers of Directors",
                "status": "in_force",
                "crossReferences": ["s 180", "s 181", "s 182", "s 184"],
            },
            {
                "sectionId": "s 588G",
                "title": "Director's duty to prevent insolvent trading",
                "content": "A director of a company has a duty to prevent the company from incurring a debt at a time when — (a) the company is insolvent at that time, or becomes insolvent by incurring that debt; and (b) at that time there are reasonable grounds for suspecting that the company is insolvent, or would so become insolvent. By failing to prevent the company from incurring the debt, the person contravenes this section if — (a) the person is aware at the time that there are grounds for suspecting insolvency; or (b) a reasonable person in a like position in a corporation in the corporation's circumstances would be so aware. Defences include that the person had reasonable grounds to expect, and did expect, that the company was solvent and would remain solvent, that the person took reasonable steps to prevent the company from incurring the debt, or that the person was ill and did not participate in management at the relevant time. Civil penalties apply under section 1317E. Criminal liability arises under section 588G(3) where the person was aware the company was insolvent or would become insolvent. This section is critical in the context of voluntary administration, receivership and liquidation proceedings.",
                "depth": 2,
                "order": 4,
                "parentSection": "Part 5.7B — Recovering Property or Compensation for the Benefit of Creditors",
                "status": "in_force",
                "crossReferences": ["s 180", "s 95A (definition of solvency and insolvency)"],
                "notes": "The safe harbour provision in s 588GA (introduced by the Treasury Laws Amendment (2017 Enterprise Incentives No. 2) Act 2017) provides protection from personal liability for insolvent trading where the director starts developing courses of action reasonably likely to lead to a better outcome for the company.",
            },
            {
                "sectionId": "s 601ED",
                "title": "When a managed investment scheme must be registered",
                "content": "A managed investment scheme must be registered under section 601EB if — (a) it has more than 20 members; or (b) it was promoted by a person, or an associate of a person, who was, when the scheme was promoted, in the business of promoting managed investment schemes; or (c) ASIC has determined in writing that the scheme must be registered. A managed investment scheme that is required to be registered must have — a responsible entity that holds an Australian financial services licence authorising it to operate the scheme, a constitution, and a compliance plan. Operating an unregistered scheme that is required to be registered is an offence with a maximum penalty of 5 years imprisonment or 200 penalty units.",
                "depth": 2,
                "order": 5,
                "parentSection": "Part 5C.1 — Registration of Managed Investment Schemes",
                "status": "in_force",
                "crossReferences": ["s 601FC (duties of responsible entity)", "s 601FD (duties of officers)"],
            },
            {
                "sectionId": "s 674",
                "title": "Continuous disclosure — listed disclosing entity bound by a disclosure requirement in market listing rules",
                "content": "If provisions of the listing rules of a prescribed financial market require a listed disclosing entity to notify the market operator of information about specified events or matters as they arise for the purpose of the market operator making that information available to participants in the market, the entity must comply with those provisions. A contravention of this section by a person who knew, or was reckless or negligent with respect to whether, the information would have a material effect on the price or value of the entity's securities is a civil penalty contravention. ASIC may seek a pecuniary penalty of up to $1,110,000 for individuals or $11,100,000 for bodies corporate, and compensation orders. Continuous disclosure obligations require timely disclosure of information that a reasonable person would expect to have a material effect on the price or value of the entity's securities.",
                "depth": 2,
                "order": 6,
                "parentSection": "Part 6CA — Continuous Disclosure",
                "status": "in_force",
                "crossReferences": ["s 677 (definition of material effect on price or value)", "s 1041H"],
                "notes": "Continuous disclosure obligations were temporarily modified during COVID-19. The Treasury Laws Amendment (2021 Measures No. 1) Act 2021 introduced a fault element for civil penalty proceedings.",
            },
            {
                "sectionId": "s 1041H",
                "title": "Misleading or deceptive conduct (financial services)",
                "content": "A person must not, in this jurisdiction, engage in conduct, in relation to a financial product or a financial service, that is misleading or deceptive or is likely to mislead or deceive. This provision mirrors section 18 of the Australian Consumer Law (Schedule 2 of the Competition and Consumer Act 2010) but applies specifically to financial products and financial services. An action for damages may be brought under section 1041I by a person who suffers loss or damage by conduct of another person that was engaged in in contravention of this section. Defences include that the person made all inquiries that were reasonable in the circumstances and, after making those inquiries, believed on reasonable grounds that the conduct was not misleading or deceptive.",
                "depth": 2,
                "order": 7,
                "parentSection": "Part 7.10 — Market Misconduct and Other Prohibited Conduct Relating to Financial Products and Services",
                "status": "in_force",
                "crossReferences": ["s 674", "cth/act-2010-109 s 18 (ACL misleading conduct)"],
            },
        ],
    },
    # ═══════════════════════════════════════════════════════════════
    # NEW SOUTH WALES (NSW) LEGISLATION
    # ═══════════════════════════════════════════════════════════════
    {
        "id": "nsw/act-2011-010",
        "jurisdiction": "NSW",
        "type": "act",
        "title": "Work Health and Safety Act 2011 (NSW)",
        "shortTitle": "WHS Act 2011 (NSW)",
        "year": 2011,
        "number": "Act No. 10 of 2011",
        "inForceDate": "2012-01-01",
        "lastAmendedDate": "2024-07-01",
        "administeredBy": "SafeWork NSW",
        "legislationUrl": "https://legislation.nsw.gov.au/view/html/inforce/current/act-2011-010",
        "relatedDocs": ["cth/act-2011-137", "qld/act-2011-018"],
        "sections": [
            {
                "sectionId": "s 19",
                "title": "Primary duty of care",
                "content": "A person conducting a business or undertaking (PCBU) must ensure, so far as is reasonably practicable, the health and safety of — (a) workers engaged, or caused to be engaged, by the person; and (b) workers whose activities in carrying out work are influenced or directed by the person; while the workers are at work in the business or undertaking. This includes providing and maintaining a work environment without risks to health and safety, providing and maintaining safe plant and structures, providing and maintaining safe systems of work, ensuring safe use, handling and storage of plant, structures and substances, providing adequate facilities for worker welfare, and providing any information, training, instruction or supervision necessary. A PCBU must also ensure that the health and safety of other persons is not put at risk from work carried out. Maximum penalty — (a) for an individual — $300,000; (b) for a body corporate — $3,000,000.",
                "depth": 2,
                "order": 0,
                "parentSection": "Part 2 — Health and Safety Duties",
                "status": "in_force",
                "crossReferences": ["s 27", "s 28", "s 31", "s 32", "s 33"],
            },
            {
                "sectionId": "s 27",
                "title": "Duty of officers",
                "content": "If a person conducting a business or undertaking has a duty or obligation under this Act, an officer of the person must exercise due diligence to ensure that the person complies with that duty or obligation. Due diligence includes — (a) acquiring and keeping up-to-date knowledge of work health and safety matters; (b) gaining an understanding of the nature of the operations and generally of the hazards and risks associated with those operations; (c) ensuring appropriate resources and processes are available and used to eliminate or minimise risks; (d) ensuring appropriate processes for receiving and considering information regarding incidents, hazards and risks; (e) ensuring the person has and implements processes for complying with duties under this Act; (f) verifying the provision and use of those resources and processes. Maximum penalty — $600,000 (if PCBU or officer) or 5 years imprisonment.",
                "depth": 2,
                "order": 1,
                "parentSection": "Part 2 — Health and Safety Duties",
                "status": "in_force",
                "crossReferences": ["s 19", "s 28", "s 268"],
            },
            {
                "sectionId": "s 28",
                "title": "Duties of workers",
                "content": "While at work, a worker must — (a) take reasonable care for his or her own health and safety; and (b) take reasonable care that his or her acts or omissions do not adversely affect the health and safety of other persons; and (c) comply, so far as the worker is reasonably able, with any reasonable instruction given by the PCBU; and (d) cooperate with any reasonable policy or procedure of the PCBU relating to health or safety at the workplace that has been notified to workers. Maximum penalty — $50,000.",
                "depth": 2,
                "order": 2,
                "parentSection": "Part 2 — Health and Safety Duties",
                "status": "in_force",
                "crossReferences": ["s 19", "s 27"],
            },
            {
                "sectionId": "s 31",
                "title": "Category 1 — Reckless conduct",
                "content": "A person commits a category 1 offence if — (a) the person has a health and safety duty; and (b) the person, without reasonable excuse, engages in conduct that exposes an individual to whom that duty is owed to a risk of death or serious injury or illness; and (c) the person is reckless as to the risk to an individual of death or serious injury or illness. Maximum penalty — (a) for an individual as a PCBU or officer — $600,000 or 5 years imprisonment; (b) for any other individual — $300,000; (c) for a body corporate — $3,000,000.",
                "depth": 2,
                "order": 3,
                "parentSection": "Part 2 — Division 5 — Offences and Penalties",
                "status": "in_force",
                "crossReferences": ["s 32", "s 33"],
            },
            {
                "sectionId": "s 32",
                "title": "Category 2 — Failure to comply with health and safety duty",
                "content": "A person commits a category 2 offence if — (a) the person has a health and safety duty; and (b) the person fails to comply with that duty; and (c) the failure exposes an individual to a risk of death or serious injury or illness. Maximum penalty — (a) for an individual as a PCBU or officer — $300,000; (b) for any other individual — $150,000; (c) for a body corporate — $1,500,000.",
                "depth": 2,
                "order": 4,
                "parentSection": "Part 2 — Division 5 — Offences and Penalties",
                "status": "in_force",
                "crossReferences": ["s 31", "s 33"],
            },
            {
                "sectionId": "s 33",
                "title": "Category 3 — Failure to comply with health and safety duty",
                "content": "A person commits a category 3 offence if — (a) the person has a health and safety duty; and (b) the person fails to comply with that duty. This does not require exposure to risk of death or serious injury. Maximum penalty — (a) for an individual as a PCBU or officer — $100,000; (b) for any other individual — $50,000; (c) for a body corporate — $500,000.",
                "depth": 2,
                "order": 5,
                "parentSection": "Part 2 — Division 5 — Offences and Penalties",
                "status": "in_force",
                "crossReferences": ["s 31", "s 32"],
            },
            {
                "sectionId": "s 268",
                "title": "Offences by officers of bodies corporate",
                "content": "If a body corporate commits an offence against this Act and the offence is proved to have been committed with the consent or connivance of, or to be attributable to any neglect on the part of, an officer of the body corporate, the officer as well as the body corporate is guilty of an offence and may be proceeded against and punished accordingly. An officer may also be prosecuted for a contravention of section 27 (duty of officers) regardless of whether the body corporate has been prosecuted for or convicted of the offence. This provision ensures individual accountability for workplace safety failures within corporate structures.",
                "depth": 2,
                "order": 6,
                "parentSection": "Part 13 — General",
                "status": "in_force",
                "crossReferences": ["s 27", "s 19"],
            },
        ],
    },
    {
        "id": "nsw/act-1900-040",
        "jurisdiction": "NSW",
        "type": "act",
        "title": "Crimes Act 1900 (NSW)",
        "shortTitle": "Crimes Act 1900",
        "year": 1900,
        "number": "Act No. 40 of 1900",
        "inForceDate": "1900-09-01",
        "lastAmendedDate": "2024-12-01",
        "administeredBy": "NSW Attorney General",
        "legislationUrl": "https://legislation.nsw.gov.au/view/html/inforce/current/act-1900-040",
        "sections": [
            {
                "sectionId": "s 18",
                "title": "Murder and manslaughter defined",
                "content": "(1)(a) Murder shall be taken to have been committed where the act of the accused, or thing by him or her omitted to be done, causing the death charged, was done or omitted with reckless indifference to human life, or with intent to kill or inflict grievous bodily harm upon some person, or done in an attempt to commit, or during or immediately after the commission, by the accused, or some accomplice with him or her, of a crime punishable by imprisonment for life or for 25 years. (1)(b) Every other punishable homicide shall be taken to be manslaughter. (2)(a) No act or omission which was not malicious, or for which the accused had lawful cause or excuse, shall be within this section. (2)(b) No punishment or forfeiture shall be incurred by any person who kills another by misfortune only.",
                "depth": 2,
                "order": 0,
                "parentSection": "Part 3 — Offences Against the Person",
                "status": "in_force",
                "crossReferences": ["s 19A", "s 24"],
            },
            {
                "sectionId": "s 19A",
                "title": "Punishment for murder",
                "content": "A person who commits the crime of murder is liable to imprisonment for life. The court shall impose a sentence of imprisonment for life on a person who is convicted of the murder of a police officer, emergency services worker, correctional officer, judicial officer, Crown prosecutor, or other specified person exercising public functions, if the murder was committed while the victim was executing their duty, and the offender knew or ought reasonably to have known that the victim was such a person. The court is not required to impose a life sentence if the court is satisfied that the person's culpability for the murder is significantly diminished by mitigating circumstances.",
                "depth": 2,
                "order": 1,
                "parentSection": "Part 3 — Offences Against the Person",
                "status": "in_force",
                "crossReferences": ["s 18", "s 21 (mandatory life sentence — certain cases)"],
            },
            {
                "sectionId": "s 24",
                "title": "Manslaughter — punishment",
                "content": "Every person who commits the crime of manslaughter shall be liable to imprisonment for 25 years.",
                "depth": 2,
                "order": 2,
                "parentSection": "Part 3 — Offences Against the Person",
                "status": "in_force",
                "crossReferences": ["s 18"],
            },
            {
                "sectionId": "s 33",
                "title": "Wounding or grievous bodily harm with intent",
                "content": "Whosoever — (a) wounds any person, or causes grievous bodily harm to any person, with intent to cause grievous bodily harm to that or any other person, or (b) is armed with any weapon, or instrument, with intent to commit any indictable offence, and wounds any person — shall be liable to imprisonment for 25 years.",
                "depth": 2,
                "order": 3,
                "parentSection": "Part 3 — Offences Against the Person",
                "status": "in_force",
                "crossReferences": ["s 35", "s 59"],
            },
            {
                "sectionId": "s 35",
                "title": "Reckless causing of grievous bodily harm in company",
                "content": "(1) A person who recklessly causes grievous bodily harm to any person is guilty of an offence. Maximum penalty — 10 years imprisonment. (2) A person who recklessly causes grievous bodily harm to any person in company is guilty of an offence. Maximum penalty — 14 years imprisonment. (3) A person who recklessly wounds any person is guilty of an offence. Maximum penalty — 7 years imprisonment. (4) A person who recklessly wounds any person in company is guilty of an offence. Maximum penalty — 10 years imprisonment. 'In company' means in the company of another person or persons.",
                "depth": 2,
                "order": 4,
                "parentSection": "Part 3 — Offences Against the Person",
                "status": "in_force",
                "crossReferences": ["s 33", "s 59"],
            },
            {
                "sectionId": "s 59",
                "title": "Assault occasioning actual bodily harm",
                "content": "Whosoever assaults any person, and thereby occasions actual bodily harm, shall be liable to imprisonment for 5 years. If committed in company, the maximum penalty is 7 years imprisonment. 'Actual bodily harm' includes any hurt or injury calculated to interfere with the health or comfort of the victim, but need not be permanent and includes psychiatric injury.",
                "depth": 2,
                "order": 5,
                "parentSection": "Part 3 — Offences Against the Person",
                "status": "in_force",
                "crossReferences": ["s 33", "s 35", "s 61"],
            },
            {
                "sectionId": "s 61",
                "title": "Common assault prosecuted by indictment",
                "content": "Whosoever assaults any person, although not occasioning actual bodily harm, shall be liable to imprisonment for 2 years. A common assault may also be dealt with summarily by a Local Court under the Criminal Procedure Act 1986, in which case the maximum penalty is 2 years imprisonment or a fine of $5,500, or both.",
                "depth": 2,
                "order": 6,
                "parentSection": "Part 3 — Offences Against the Person",
                "status": "in_force",
                "crossReferences": ["s 59"],
            },
            {
                "sectionId": "s 117",
                "title": "Breaking etc into any house etc and committing serious indictable offence",
                "content": "Whosoever breaks and enters any dwelling-house or other building and commits any serious indictable offence therein shall be liable to imprisonment for 14 years. Whosoever breaks out of any dwelling-house or other building after having committed any serious indictable offence therein shall be liable to imprisonment for 14 years. Whosoever enters any dwelling-house or other building with intent to commit any serious indictable offence therein shall be liable to imprisonment for 10 years. If committed in circumstances of aggravation (while armed with an offensive weapon, or in company, or where the accused uses corporal violence on any person), the maximum penalty is 20 years imprisonment.",
                "depth": 2,
                "order": 7,
                "parentSection": "Part 4 — Offences Relating to Property",
                "status": "in_force",
                "crossReferences": ["s 112 (breaking and entering)", "s 192E (fraud)"],
            },
            {
                "sectionId": "s 192E",
                "title": "Fraud",
                "content": "(1) A person who, by any deception, dishonestly — (a) obtains property belonging to another, or (b) obtains any financial advantage or causes any financial disadvantage, is guilty of the offence of fraud. Maximum penalty — 10 years imprisonment. (2) A person's obtaining of property belonging to another may be dishonest even if the person is willing to pay for the property. (3) For the purposes of this Part, 'deception' means any deception, by words or other conduct, as to fact or as to law, including — (a) a deception as to the intentions of the person using the deception or any other person, and (b) conduct by a person that causes a computer, a machine or an electronic device to make a response that the person is not authorised to cause it to make.",
                "depth": 2,
                "order": 8,
                "parentSection": "Part 4AA — Fraud",
                "status": "in_force",
                "crossReferences": ["s 192F (intention to defraud by destroying or concealing accounting records)", "s 117"],
            },
        ],
    },
    {
        "id": "nsw/act-1979-203",
        "jurisdiction": "NSW",
        "type": "act",
        "title": "Environmental Planning and Assessment Act 1979 (NSW)",
        "shortTitle": "EP&A Act 1979",
        "year": 1979,
        "number": "Act No. 203 of 1979",
        "inForceDate": "1980-09-01",
        "lastAmendedDate": "2024-12-01",
        "administeredBy": "Department of Planning and Environment",
        "legislationUrl": "https://legislation.nsw.gov.au/view/html/inforce/current/act-1979-203",
        "sections": [
            {
                "sectionId": "s 1.3",
                "title": "Objects of Act",
                "content": "The objects of this Act are as follows — (a) to promote the social and economic welfare of the community and a better environment by the proper management, development and conservation of the State's natural and other resources; (b) to facilitate ecologically sustainable development by integrating relevant economic, environmental and social considerations in decision-making about environmental planning and assessment; (c) to promote the orderly and economic use and development of land; (d) to promote the delivery and maintenance of affordable housing; (e) to protect the environment, including the conservation of threatened and other species of native animals and plants, ecological communities and their habitats; (f) to promote the sustainable management of built and cultural heritage (including Aboriginal cultural heritage); (g) to promote good design and amenity of the built environment; (h) to promote the proper construction and maintenance of buildings, including the protection of the health and safety of their occupants; (i) to promote the sharing of the responsibility for environmental planning and assessment between the different levels of government in the State; (j) to provide increased opportunity for community participation in environmental planning and assessment.",
                "depth": 1,
                "order": 0,
                "status": "in_force",
            },
            {
                "sectionId": "s 4.1",
                "title": "Environmental planning instruments",
                "content": "Environmental planning instruments comprise — (a) State environmental planning policies (SEPPs), which deal with matters of State or regional environmental planning significance, and (b) local environmental plans (LEPs), which guide planning decisions for local government areas. Environmental planning instruments may make provision for or with respect to protecting the environment (including the coastal environment), managing or conserving natural resources or cultural heritage, development or the use of land, and any other matter relating to planning. The Minister may direct the preparation of, or make, a State environmental planning policy. A council may prepare a draft local environmental plan for its area.",
                "depth": 2,
                "order": 1,
                "parentSection": "Part 4 — Development Assessment",
                "status": "in_force",
                "crossReferences": ["s 4.16", "s 4.46"],
            },
            {
                "sectionId": "s 4.16",
                "title": "Determination of development applications",
                "content": "A consent authority is to determine a development application by — (a) granting consent to the application, either unconditionally or subject to conditions, or (b) refusing consent to the application. In determining a development application, a consent authority is to take into consideration such of the following matters as are of relevance — (a) the provisions of any environmental planning instrument applying to the land; (b) the provisions of any proposed instrument that is or has been the subject of public consultation and has been notified to the consent authority; (c) any development control plan; (d) any planning agreement; (e) the regulations; (f) the likely impacts of the development, including environmental impacts on both the natural and built environments, and social and economic impacts in the locality; (g) the suitability of the site for the development; (h) submissions made in accordance with the Act; (i) the public interest.",
                "depth": 2,
                "order": 2,
                "parentSection": "Part 4 — Development Assessment",
                "status": "in_force",
                "crossReferences": ["s 4.1", "s 4.55", "s 9.45"],
            },
            {
                "sectionId": "s 4.46",
                "title": "Complying development certificates",
                "content": "If development is specified as complying development by an environmental planning instrument, the development may be carried out if a complying development certificate has been issued by a council or an accredited certifier, and the development is carried out in accordance with the certificate and any conditions attached to it. A complying development certificate must not be issued unless the proposed development complies with all applicable development standards of the relevant environmental planning instrument and the development control plan. Complying development provides a fast-track alternative to the standard development application process for straightforward development that meets predetermined standards. The certificate has effect as a development consent.",
                "depth": 2,
                "order": 3,
                "parentSection": "Part 4 — Development Assessment",
                "status": "in_force",
                "crossReferences": ["s 4.1", "s 4.16"],
            },
            {
                "sectionId": "s 4.55",
                "title": "Modification of consents",
                "content": "(1) A consent authority may, on application being made by the applicant or any other person entitled to act on a consent, modify the consent if — (a) the modification involves minimal environmental impact and is substantially the same development (s 4.55(1A)); or (b) the development to which the consent as modified relates is substantially the same development (s 4.55(2)), in which case the consent authority must consider any submissions received and the matters referred to in section 4.15(1). The modification must not result in a development that is substantially different from the originally approved development. The consent authority may also modify a consent to correct a minor error, misdescription or miscalculation (s 4.55(1)). An application for modification of a consent must be determined within the period prescribed by the regulations.",
                "depth": 2,
                "order": 4,
                "parentSection": "Part 4 — Development Assessment",
                "status": "in_force",
                "crossReferences": ["s 4.16", "s 9.45"],
            },
            {
                "sectionId": "s 7.1",
                "title": "Infrastructure contributions",
                "content": "Part 7 of the Act establishes a framework for the collection of development contributions to fund the provision of local infrastructure and State infrastructure. Contributions may be imposed through — (a) conditions of development consent requiring the payment of a monetary contribution or the dedication of land free of cost (local infrastructure contributions under s 7.11); (b) a contributions plan under section 7.18; (c) a planning agreement between a developer and a planning authority under section 7.4; or (d) a special infrastructure contribution determined by the Minister (s 7.24). Contributions must be reasonable and related to the proposed development and the demand for public infrastructure generated by the development.",
                "depth": 2,
                "order": 5,
                "parentSection": "Part 7 — Infrastructure and Contributions",
                "status": "in_force",
                "crossReferences": ["s 4.16"],
            },
            {
                "sectionId": "s 9.45",
                "title": "Class 1 — Environmental planning and protection appeals",
                "content": "The Land and Environment Court has jurisdiction to hear and dispose of appeals under this Act. Class 1 of the Court's jurisdiction includes — (a) appeals by applicants against the determination of a development application (including a refusal or the imposition of conditions); (b) appeals against a failure to determine a development application within the prescribed period; (c) appeals against the modification or refusal to modify a development consent. The Court exercises a merits review function in Class 1 proceedings, meaning it stands in the shoes of the original consent authority and makes a fresh determination on the merits. Class 4 proceedings involve civil enforcement of planning law, including injunctions to restrain breaches of the Act or conditions of consent.",
                "depth": 2,
                "order": 6,
                "parentSection": "Part 9 — Reviews and Appeals",
                "status": "in_force",
                "crossReferences": ["s 4.16", "s 4.55"],
            },
        ],
    },
    {
        "id": "nsw/act-2010-042",
        "jurisdiction": "NSW",
        "type": "act",
        "title": "Residential Tenancies Act 2010 (NSW)",
        "shortTitle": "Residential Tenancies Act 2010",
        "year": 2010,
        "number": "Act No. 42 of 2010",
        "inForceDate": "2010-01-31",
        "lastAmendedDate": "2024-12-01",
        "administeredBy": "NSW Fair Trading",
        "legislationUrl": "https://legislation.nsw.gov.au/view/html/inforce/current/act-2010-042",
        "sections": [
            {
                "sectionId": "s 3",
                "title": "Object of Act",
                "content": "The object of this Act is to establish a legislative framework that balances the interests of landlords and tenants in residential tenancy agreements, and that provides appropriate measures for the resolution of disputes between the parties to such agreements.",
                "depth": 1,
                "order": 0,
                "status": "in_force",
            },
            {
                "sectionId": "s 13",
                "title": "Standard form of residential tenancy agreement",
                "content": "A residential tenancy agreement is taken to include the terms set out in the standard form prescribed by the regulations. These standard terms cannot be varied or excluded by the parties and cover matters including the identification of the premises, the amount of rent, the amount of the rental bond, the term of the agreement, the obligations of the landlord and tenant, and the circumstances in which the agreement may be terminated. Any term of a residential tenancy agreement that is inconsistent with a term set out in the standard form is void to the extent of the inconsistency.",
                "depth": 2,
                "order": 1,
                "parentSection": "Part 2 — Residential Tenancy Agreements",
                "status": "in_force",
                "crossReferences": ["s 40", "s 62"],
            },
            {
                "sectionId": "s 40",
                "title": "Rent increases",
                "content": "The rent payable under a residential tenancy agreement may not be increased during a fixed term of the agreement unless the agreement specifies the amount of the increase or the method by which the increase is to be calculated. Rent may not be increased more than once in any period of 12 months. The landlord must give the tenant at least 60 days written notice of a rent increase. The tenant may apply to the Tribunal for an order that the increased rent is excessive. In determining whether a rent increase is excessive, the Tribunal must have regard to the general market level of rents for comparable premises in the locality, the landlord's outgoings under the agreement, and any work done to the premises by the landlord.",
                "depth": 2,
                "order": 2,
                "parentSection": "Part 3 — Rent and Other Payments",
                "status": "in_force",
                "crossReferences": ["s 13", "s 187"],
            },
            {
                "sectionId": "s 62",
                "title": "Landlord's general obligations — repairs",
                "content": "A landlord must provide the residential premises in a reasonable state of cleanliness and fit for habitation by the tenant, and must maintain the premises in a reasonable state of repair during the tenancy, having regard to the age of, the rent payable for, and the prospective life of the premises. The landlord is not in breach of this duty if the state of disrepair was caused by the tenant's breach of the agreement. If the premises require urgent repairs (such as a burst water service, a blocked or broken lavatory system, a serious roof leak, a gas leak, a dangerous electrical fault, flooding, or serious storm or fire damage), the tenant may arrange the repairs if the tenant cannot contact the landlord or the landlord's agent after making reasonable attempts, and the cost of the repairs does not exceed $1,000 (or such other amount as prescribed). The landlord must reimburse the tenant for the reasonable cost of the repairs.",
                "depth": 2,
                "order": 3,
                "parentSection": "Part 4 — Rights and Obligations of Landlords and Tenants",
                "status": "in_force",
                "crossReferences": ["s 13", "s 187"],
            },
            {
                "sectionId": "s 85",
                "title": "Termination by tenant — breach by landlord",
                "content": "A tenant may give a termination notice to the landlord if the landlord has breached the residential tenancy agreement. Before giving the notice, the tenant must give the landlord a written notice specifying the breach and allowing a period of not less than 14 days for the landlord to remedy the breach. If the landlord fails to remedy the breach within the specified period, the tenant may give a termination notice specifying a termination date that is not earlier than 14 days after the notice is given. If the breach causes or is likely to cause injury or danger to persons, or significant property damage, or results in the tenant being deprived of the use of the premises, the tenant may give a termination notice without first giving a notice to remedy.",
                "depth": 2,
                "order": 4,
                "parentSection": "Part 5 — Termination of Residential Tenancy Agreements",
                "status": "in_force",
                "crossReferences": ["s 87", "s 100", "s 187"],
            },
            {
                "sectionId": "s 87",
                "title": "Termination by landlord — breach by tenant",
                "content": "A landlord may give a termination notice to the tenant if the tenant has breached the residential tenancy agreement. Before giving the notice, the landlord must give the tenant a written notice specifying the breach and allowing a period of not less than 14 days for the tenant to remedy the breach. If the tenant fails to remedy the breach within the specified period, the landlord may give a termination notice specifying a termination date that is not earlier than 14 days after the notice is given. If the breach relates to non-payment of rent and the rent remains unpaid for 14 days after falling due, the landlord may give a termination notice without first giving a notice to remedy, and the termination date must not be earlier than the day after the notice is given. If the tenant remedies the breach before the termination date, the notice is taken to be withdrawn.",
                "depth": 2,
                "order": 5,
                "parentSection": "Part 5 — Termination of Residential Tenancy Agreements",
                "status": "in_force",
                "crossReferences": ["s 85", "s 100", "s 187"],
            },
            {
                "sectionId": "s 100",
                "title": "Termination at end of fixed term — no grounds",
                "content": "A landlord may, without specifying a ground of termination, give a termination notice to a tenant at or before the end of the fixed term of a residential tenancy agreement. The termination notice must specify a termination date that is not earlier than 30 days after the day on which the notice is given and not earlier than the last day of the fixed term. For periodic agreements, the notice must specify a termination date that is not earlier than 90 days after the day on which the notice is given. The Tribunal must, on application by the landlord, make a termination order if satisfied that a termination notice was given in accordance with this section and the tenant has not vacated the premises.",
                "depth": 2,
                "order": 6,
                "parentSection": "Part 5 — Termination of Residential Tenancy Agreements",
                "status": "in_force",
                "crossReferences": ["s 85", "s 87", "s 187"],
                "notes": "NSW has introduced reforms limiting no-grounds termination. From 2025, landlords will be required to provide a specified reason for ending a tenancy, effectively abolishing no-grounds evictions for both fixed-term and periodic agreements.",
            },
            {
                "sectionId": "s 187",
                "title": "Tribunal orders — general",
                "content": "The NSW Civil and Administrative Tribunal (NCAT) may, on application by a landlord or a tenant, make such orders as it considers appropriate to resolve a dispute arising under a residential tenancy agreement. Orders the Tribunal may make include — (a) an order declaring the rights and obligations of the parties; (b) an order requiring the payment of an amount of money (including compensation for breach); (c) a termination order ending the residential tenancy agreement; (d) an order for specific performance of an obligation under the agreement; (e) an order restraining a party from engaging in specified conduct; (f) an order varying, or setting aside in whole or in part, a residential tenancy agreement. The Tribunal must not make an order for possession of the premises unless it has made or is making a termination order. An urgent application may be made to the Tribunal without notice to the other party in cases involving threatened violence, risk to safety, or imminent loss of the premises.",
                "depth": 2,
                "order": 7,
                "parentSection": "Part 8 — Resolution of Disputes",
                "status": "in_force",
                "crossReferences": ["s 85", "s 87", "s 100"],
            },
        ],
    },
]


def main():
    parser = argparse.ArgumentParser(description="Seed CTH and NSW legislation into PACT Hub")
    parser.add_argument("--base-url", default=os.environ.get("PACT_BASE_URL", DEFAULT_BASE))
    parser.add_argument("--admin-key", default=os.environ.get("ADMIN_SECRET", os.environ.get("PACT_ADMIN_SECRET", "")))
    args = parser.parse_args()

    base = args.base_url.rstrip("/")
    admin_key = args.admin_key

    if not admin_key:
        print("ERROR: No admin key provided. Set ADMIN_SECRET env var or use --admin-key")
        sys.exit(1)

    print(f"Seeding {len(CTH_NSW_ACTS)} CTH/NSW legislation documents to {base}")
    print(f"Total sections: {sum(len(a.get('sections', [])) for a in CTH_NSW_ACTS)}")
    print()

    # Ingest all documents in one call
    url = f"{base}/api/axiom/legislation/ingest"
    headers = {
        "Content-Type": "application/json",
        "X-Admin-Key": admin_key,
    }

    resp = requests.post(url, json={"documents": CTH_NSW_ACTS}, headers=headers, timeout=60)

    if resp.status_code != 200:
        print(f"FAILED: HTTP {resp.status_code}")
        print(resp.text[:500])
        sys.exit(1)

    data = resp.json()
    print(f"SUCCESS: Ingested {data['ingested']} documents")
    for doc in data.get("documents", []):
        print(f"  {doc['id']:30s}  {doc['sectionsInserted']:3d} sections  {doc['title']}")

    print()
    print(f"Total sections ingested: {sum(d['sectionsInserted'] for d in data.get('documents', []))}")
    print()
    print("API endpoints now available:")
    print(f"  GET {base}/api/axiom/legislation?jurisdiction=CTH")
    print(f"  GET {base}/api/axiom/legislation?jurisdiction=NSW")
    print(f"  GET {base}/api/axiom/legislation/cth%2Fact-2009-028")
    print(f"  GET {base}/api/axiom/legislation/search?q=unfair+dismissal&jurisdiction=CTH")
    print(f"  GET {base}/api/axiom/legislation/nsw%2Fact-1900-040?section=s%2018&format=text")


if __name__ == "__main__":
    main()
