#!/usr/bin/env python3
"""
Seed the Liquor Act 1992 (Qld) + Liquor Regulation 2002 (Qld) into PACT's
Structured Legislation API. Refs #5091 (child of epic #5114, cold-eye review
remediation finding 4 — public-statute coverage).

The Liquor Act 1992 is the load-bearing instrument for any nightlife /
hospitality document (BCC nightlife-economy story): liquor licensing, trading
hours, safe night precincts and ID scanning are exclusively STATE powers
exercised by the Commissioner for Liquor and Gaming under this Act — local
government competence is limited to land-use planning under the Planning Act
2016 and local nuisance enforcement.

Ingestion path (per the #5091 triage comment): this is the established
CURATED-SEED pattern used for every QLD act already in the graph
(`seed_qld_legislation.py`) — a POST to the admin
`/api/axiom/legislation/ingest` endpoint. It deliberately does NOT ride the
QLD Legislation API live-fetch machinery (`api.legislation.qld.gov.au`),
which is broken and tracked separately in #2901.

Provenance: section numbering, titles and content were verified on
2026-08-12 against the official in-force reprints on
www.legislation.qld.gov.au (whole-view HTML for `act-1992-021` and
`sl-2002-0212`). Content is summarised for agent consumption (not full
gazette text), same convention as the other curated legislation seeds.

Usage:
    python scripts/seed_qld_liquor_legislation.py [--base-url URL] [--admin-key KEY]

Defaults:
    --base-url https://pact.tailor.au
    --admin-key (reads from ADMIN_SECRET env var)

Idempotent: the ingest endpoint upserts documents and delete-reinserts
sections, so re-running (e.g. on every cd-source deploy) is safe.
"""

import requests
import os
import sys
import argparse

# ── Configuration ──────────────────────────────────────────────────
DEFAULT_BASE = "https://pact.tailor.au"

# ── Liquor legislation data ────────────────────────────────────────
# Verified against legislation.qld.gov.au in-force reprints (2026-08-12).

LIQUOR_DOCS = [
    {
        "id": "qld/act-1992-021",
        "jurisdiction": "QLD",
        "type": "act",
        "title": "Liquor Act 1992 (Qld)",
        "shortTitle": "Liquor Act 1992",
        "year": 1992,
        "number": "Act No. 21 of 1992",
        "administeredBy": "Office of Liquor and Gaming Regulation, Department of Justice",
        "legislationUrl": "https://www.legislation.qld.gov.au/view/whole/html/inforce/current/act-1992-021",
        "relatedDocs": ["qld/reg-2002-212"],
        "sections": [
            {"sectionId": "s 3", "title": "Main purposes of Act", "content": "The main purposes of this Act are — (a) to regulate the liquor industry, and areas in the vicinity of licensed premises, in a way compatible with minimising harm and the potential for harm from alcohol abuse and misuse and associated violence, minimising adverse effects on the health or safety of members of the public, and minimising adverse effects on the amenity of the community; (b) to facilitate and regulate the optimum development of the tourist, liquor and hospitality industries of the State having regard to the welfare, needs and interests of the community and the economic implications of change; (c) to provide for the jurisdiction of the tribunal to hear and decide reviews of certain decisions under this Act; (d) to provide a flexible, practical system for regulation of the liquor industry with minimal formality, technicality or intervention; (e) to regulate the sale and supply of liquor in particular areas to minimise harm caused by alcohol abuse and misuse and associated violence; (f) to regulate the provision of adult entertainment; (g) to provide revenue for the State.", "depth": 1, "order": 0, "parentSection": "Part 1 — Preliminary", "status": "in_force", "crossReferences": ["s 3A"]},
            {"sectionId": "s 3A", "title": "Principle underlying this Act for facilitating and regulating the liquor industry", "content": "The underlying principle of this Act in relation to the sale and supply of liquor is that a person may obtain a licence to sell or supply liquor as part of conducting a business on premises, and liquor may only be sold or supplied on the licensed premises as part of conducting a business, on the licensed premises, that is the principal activity under the licence. The Act states the principal activity of a business that may be conducted under each type of licence, and must be administered in accordance with the underlying principle, subject to the harm-minimisation main purpose in section 3(a).", "depth": 2, "order": 1, "parentSection": "Part 1 — Preliminary", "status": "in_force", "crossReferences": ["s 3", "s 58"]},
            {"sectionId": "s 4", "title": "Definitions", "content": "Dictionary for the Act. Key defined terms include: 'amenity', of a community or locality — the atmosphere, ambience, character and pleasantness of the community or locality, and the health, safety, comfort and enjoyment of persons who live in, work in or visit it; 'approved training course' — a course, prescribed under a regulation, about the responsible service of liquor (see Liquor Regulation 2002 s 38); 'approved extended trading hours' — the trading hours mentioned in an extended trading hours approval endorsed on the licence; '3a.m. safe night precinct', 'banning order', 'approved ID scanner' and 'approved ID scanning system' (see Part 6AA); 'unreasonable noise' — noise exceeding limits prescribed by regulation (see Liquor Regulation 2002 s 40).", "depth": 2, "order": 2, "parentSection": "Part 1 — Preliminary", "status": "in_force", "crossReferences": ["s 9A", "Liquor Regulation 2002 r 38", "Liquor Regulation 2002 r 40"]},
            {"sectionId": "s 9", "title": "Ordinary trading hours", "content": "The authority conferred by a licence to sell liquor during ordinary trading hours extends only to the hours that are, under this section, the ordinary trading hours of the premises. Subject to stated exceptions, on any day other than Good Friday or Christmas Day the ordinary trading hours of licensed premises are between 10a.m. and 12 midnight. For a commercial special facility licence for an airport or casino, ordinary hours are 5a.m. to 12 midnight. For takeaway liquor sold under a commercial hotel licence, community club licence, commercial special facility licence or subsidiary on-premises licence (meals), ordinary hours are 10a.m. to 10p.m. On Anzac Day, ordinary trading hours generally exclude any period before 1p.m. (with dining and RSL/Services Club exceptions from 5a.m.). The commissioner may by order reduce the trading hours of specified premises. Trading hours are set by this Act and the commissioner — not by local governments.", "depth": 2, "order": 3, "parentSection": "Part 1 — Preliminary", "status": "in_force", "crossReferences": ["s 84", "s 86", "s 161"]},
            {"sectionId": "s 9A", "title": "When a person may be taken to be unduly intoxicated", "content": "A person may be taken to be unduly intoxicated if the person's speech, balance, coordination or behaviour is noticeably affected, and there are reasonable grounds for believing the affected speech, balance, coordination or behaviour is the result of the consumption of liquor, drugs or another intoxicating substance.", "depth": 2, "order": 4, "parentSection": "Part 1 — Preliminary", "status": "in_force", "crossReferences": ["s 156", "s 165", "s 165A"]},
            {"sectionId": "s 58", "title": "Available licences", "content": "The following licences may be granted and held under this Act — (a) commercial hotel licence; (b) commercial special facility licence; (c) commercial other licence; (d) community club licence; (e) community other licence; (f) nightclub licence. Only 1 licence may be granted or held for premises or part of premises (with a stated exception for premises also licensed under the Wine Industry Act 1994, where the licensee must be the same person).", "depth": 2, "order": 10, "parentSection": "Part 4 — Licences", "status": "in_force", "crossReferences": ["s 59", "s 66"]},
            {"sectionId": "s 59", "title": "Principal activity of a business conducted under a commercial hotel licence", "content": "The principal activity of a business conducted under a commercial hotel licence is the sale of liquor for consumption on the licensed premises, or on and off the premises, together with the provision of meals and accommodation as required under the licence, and the provision of premises and catering facilities for functions. The authority to sell liquor does not apply unless a business with that principal activity is conducted on the premises. It is declared inconsistent with the principal activity to only sell liquor for consumption off the premises.", "depth": 2, "order": 11, "parentSection": "Part 4 — Licences", "status": "in_force", "crossReferences": ["s 58", "s 60"]},
            {"sectionId": "s 60", "title": "Authority of commercial hotel licence", "content": "A commercial hotel licence authorises the licensee to sell liquor on the licensed premises for consumption on or off the premises during ordinary trading hours or approved extended trading hours; to sell liquor at any time to a resident on the premises (and, for on-premises consumption, to a guest in the resident's company); and to sell liquor on premises approved by the commissioner (detached bottle shops) for consumption off the premises. If stated in the licence, the authority extends to catering for functions off the premises. The authority is subject to this Act and the conditions stated in the licence.", "depth": 2, "order": 12, "parentSection": "Part 4 — Licences", "status": "in_force", "crossReferences": ["s 9", "s 59", "s 84"]},
            {"sectionId": "s 66", "title": "Types of commercial other licence", "content": "The following types of commercial other licence may be granted and held under this Act — (a) subsidiary on-premises licence; (b) subsidiary off-premises licence; (c) bar licence; (d) industrial canteen licence; (e) producer/wholesaler licence; (f) artisan producer licence.", "depth": 2, "order": 13, "parentSection": "Part 4 — Licences", "status": "in_force", "crossReferences": ["s 58"]},
            {"sectionId": "s 84", "title": "Authority of extended trading hours approval", "content": "An extended trading hours approval authorises the licensee who holds the approval to sell liquor on a regular basis under authority of the licence for the premises for which the approval is granted, at the times and subject to the conditions stated in the approval. Failure to comply with the times or conditions is, under section 136, a ground for the commissioner to take disciplinary action relating to the licence.", "depth": 2, "order": 20, "parentSection": "Part 4 — Licences", "status": "in_force", "crossReferences": ["s 86", "s 9"]},
            {"sectionId": "s 86", "title": "Hours to which application may relate etc.", "content": "An application for an extended trading hours approval may seek regular trading — (a) for a commercial special facility licence relating to an airport or casino: between 12a.m. and 5a.m.; (b) for a licence relating to premises in a safe night precinct: between 12a.m. and 3a.m.; (c) otherwise: between 12a.m. and 2a.m. A subsidiary on-premises licence (meals) or artisan producer licence may seek trading only to 1a.m. Early-morning extensions (9–10a.m., 7–9a.m. for particular licences and functions) are also available; for several categories the applicant must satisfy the commissioner of a demonstrated community need. The late-trading ceilings — 2a.m. generally, 3a.m. in a safe night precinct — are set by this State Act; they are not within local government power to vary, although development approval conditions are among the matters the commissioner must consider under section 121.", "depth": 2, "order": 21, "parentSection": "Part 4 — Licences", "status": "in_force", "crossReferences": ["s 84", "s 121", "s 173NC"]},
            {"sectionId": "s 116", "title": "When community impact statement to be given to commissioner", "content": "Applications for a licence (other than a community other licence), for a variation of licence under section 111, or for an extended trading hours approval mentioned in section 86(1), must be accompanied by a community impact statement. The commissioner may waive the requirement in stated circumstances (no significant change, remote location, purpose achieved by other means, or other special circumstances). The statement's purpose is to help the commissioner assess the impact on the community, having regard to the harm-minimisation main purpose in section 3(a). It must address population and demographic trends, likely health and social impacts, their magnitude, duration and probability, and proximity to sub-communities such as schools and places of worship.", "depth": 2, "order": 30, "parentSection": "Part 5 — Grant, variation and transfer of licences and permits and related matters", "status": "in_force", "crossReferences": ["s 3", "s 86", "s 121"]},
            {"sectionId": "s 119", "title": "Objection by member of public to grant of applications", "content": "If notice of an application is published as required by section 118, any member of the public (an adult individual or body that has a proper interest in the locality and is likely to be affected) may object to the grant, individually or by petition. Grounds include: undue offence, annoyance, disturbance or inconvenience to persons who reside, work or do business in the locality, or to persons in or travelling to or from a place of public worship, hospital or school; harm from alcohol abuse and misuse and associated violence; adverse effect on the health or safety of members of the public; and adverse effect on the amenity of the community.", "depth": 2, "order": 31, "parentSection": "Part 5 — Grant, variation and transfer of licences and permits and related matters", "status": "in_force", "crossReferences": ["s 121"]},
            {"sectionId": "s 121", "title": "Matters the commissioner must have regard to", "content": "In deciding whether to grant an application, the commissioner must have regard to: the community impact statement matters and the public interest as it relates to harm minimisation and community amenity; objections and comments made under sections 117–119A; the impact on the amenity of the community; for extended trading hours applications, the applicant's previous conduct, the applicant's ability to control the noise and behaviour of the number of persons expected on and in the vicinity of the premises, and the suitability of the premises; and any relevant conditions imposed on a development approval that relates to the premises. This is the statutory junction between State liquor licensing and local-government planning: council influence enters through development approval conditions considered by the commissioner, not through any council power over the licence itself.", "depth": 2, "order": 32, "parentSection": "Part 5 — Grant, variation and transfer of licences and permits and related matters", "status": "in_force", "crossReferences": ["s 116", "s 119", "s 86"]},
            {"sectionId": "s 142ZZ", "title": "Unacceptable practices and promotions", "content": "A licensee or permittee must not engage in, or allow another person to engage in, an unacceptable practice or promotion in the conduct of business on the relevant premises. Maximum penalty — 100 penalty units. Unacceptable practices or promotions include those that may encourage irresponsible consumption of liquor, discourage a patron from monitoring or controlling their consumption, are likely to have special appeal to children, are indecent or offensive, use emotive descriptions likely to encourage irresponsible consumption, involve free or discounted drinks in a way that encourages excessive or rapid consumption, or are prescribed by regulation.", "depth": 2, "order": 40, "parentSection": "Part 6 — Obligatory provisions and offences", "status": "in_force", "crossReferences": ["Liquor Regulation 2002 r 41"]},
            {"sectionId": "s 155", "title": "Minors on premises", "content": "A licensee, permittee or person in control of premises to which a licence or permit relates must ensure that a minor (other than an exempt minor) is not on the premises, and an employee or agent must not allow a minor to enter. If a minor is on the premises the licensee or permittee, any other person in control, and any employee or agent who allowed entry each commit an offence. Maximum penalty — 100 penalty units. 'Exempt minor' includes a resident, a minor performing employment or training duties, a minor attending a function, a minor eating a meal, or a minor accompanied by a responsible adult who is responsibly supervising the minor — but on nightclub-licensed premises a minor is not exempt after 5p.m. merely because they are eating a meal or accompanied by a responsible adult.", "depth": 2, "order": 50, "parentSection": "Part 6 — Obligatory provisions and offences", "status": "in_force", "crossReferences": ["s 155A", "s 156", "s 165A"]},
            {"sectionId": "s 155A", "title": "Prohibition on sale to a minor", "content": "A person must not sell liquor to a minor. Maximum penalty — (a) if the person is the licensee or permittee of, or an approved manager working at, the premises to which a licence or permit relates — 250 penalty units; (b) in any other case — 80 penalty units.", "depth": 2, "order": 51, "parentSection": "Part 6 — Obligatory provisions and offences", "status": "in_force", "crossReferences": ["s 155", "s 156"]},
            {"sectionId": "s 155AI", "title": "Prohibition on sale or supply of rapid intoxication drinks during restricted period", "content": "A licensee or permittee must not, during the restricted period, sell or supply a rapid intoxication drink at the premises. Maximum penalty — 100 penalty units. The prohibition does not apply to the extent an exemption granted under section 155AK is in force for the premises. Rapid intoxication drinks (shots, high-alcohol mixed drinks and similar) are prescribed by regulation.", "depth": 2, "order": 52, "parentSection": "Part 6 — Obligatory provisions and offences", "status": "in_force", "crossReferences": ["Liquor Regulation 2002 r 41B"]},
            {"sectionId": "s 156", "title": "Liquor prohibited to certain persons", "content": "A person must not, on premises to which a licence or permit relates, supply liquor to, permit or allow liquor to be supplied to, or allow liquor to be consumed by, a person who is a minor or who is unduly intoxicated or disorderly. A person must not supply liquor to a minor on a street or place adjacent to licensed premises or in a public place, and must not send a minor to licensed premises to be supplied with liquor. Maximum penalty for a licensee, permittee or approved manager — 250 penalty units where the person is a minor, 500 penalty units where the person is unduly intoxicated or disorderly; otherwise 80 penalty units.", "depth": 2, "order": 53, "parentSection": "Part 6 — Obligatory provisions and offences", "status": "in_force", "crossReferences": ["s 9A", "s 155A", "s 156A"]},
            {"sectionId": "s 156A", "title": "Irresponsible supply of liquor to a minor at a private place etc.", "content": "An adult must not supply liquor to a minor at a private place unless the adult is a responsible adult for the minor, and a responsible adult must not supply liquor to the minor at a private place unless the supply is consistent with the responsible supervision of the minor. Maximum penalty — 80 penalty units. Relevant factors for responsible supervision include whether the adult or minor is unduly intoxicated, the minor's age, whether the liquor is consumed with food, whether consumption is supervised, and the quantity supplied and period of supply.", "depth": 2, "order": 54, "parentSection": "Part 6 — Obligatory provisions and offences", "status": "in_force", "crossReferences": ["s 156"]},
            {"sectionId": "s 161", "title": "Consumption or removal of liquor outside trading hours", "content": "A person must not consume liquor on, remove liquor from, or receive liquor from anyone on, premises to which a licence or permit relates at any time other than a time when liquor may be sold to, or consumed by, the person on the premises, or be removed from the premises by the person, under authority of the licence or permit. Maximum penalty — 25 penalty units.", "depth": 2, "order": 55, "parentSection": "Part 6 — Obligatory provisions and offences", "status": "in_force", "crossReferences": ["s 9"]},
            {"sectionId": "s 164", "title": "Conduct causing public nuisance", "content": "A person must not be drunk or disorderly, or create a disturbance, in premises to which a licence or permit relates. Maximum penalty — 25 penalty units.", "depth": 2, "order": 56, "parentSection": "Part 6 — Obligatory provisions and offences", "status": "in_force", "crossReferences": ["s 165"]},
            {"sectionId": "s 165", "title": "Removal of persons from premises", "content": "An authorised person (the licensee or permittee, or their employee or agent) may require a person to leave the premises if the person is unduly intoxicated, disorderly, creating a disturbance, a non-exempt minor, has entered despite refusal under section 165A, or refuses to state particulars or produce evidence of age under section 167. A person must immediately leave when required (maximum penalty — 50 penalty units); if the person fails to leave, necessary and reasonable force may be used, and resisting removal is an offence (50 penalty units).", "depth": 2, "order": 57, "parentSection": "Part 6 — Obligatory provisions and offences", "status": "in_force", "crossReferences": ["s 9A", "s 165A"]},
            {"sectionId": "s 165A", "title": "Refusing entry to premises", "content": "An authorised person may refuse entry to premises to a person who is unduly intoxicated or disorderly, a non-exempt minor, a suspected minor who fails to produce acceptable evidence of age, or where entry would breach a licence condition. A person must not enter or attempt to enter after being refused (maximum penalty — 50 penalty units); necessary and reasonable force may be used to prevent entry, and resisting is an offence (50 penalty units).", "depth": 2, "order": 58, "parentSection": "Part 6 — Obligatory provisions and offences", "status": "in_force", "crossReferences": ["s 155", "s 165"]},
            {"sectionId": "s 169", "title": "Authority required for sale", "content": "A person must not sell liquor unless the sale is made under the authority of a licence or permit (for wine, under this Act or the Wine Industry Act 1994). Maximum penalty — (a) first offence: 500 penalty units; (b) second offence: 700 penalty units or 6 months imprisonment; (c) third or later offence: 1,000 penalty units or 18 months imprisonment. This is the core prohibition making the sale of liquor in Queensland lawful only under a State-issued licence or permit.", "depth": 2, "order": 60, "parentSection": "Part 6 — Obligatory provisions and offences", "status": "in_force", "crossReferences": ["s 58", "s 171"]},
            {"sectionId": "s 171", "title": "Carrying or exposing liquor for sale", "content": "A person must not carry or expose liquor for sale in any premises without the authority of a licence or permit relating to the premises. Maximum penalty — 500 penalty units for a first offence, rising to 1,000 penalty units or 18 months imprisonment for a third or later offence. In proceedings, the burden of proving liquor was not carried or exposed for sale lies on the person alleged to have carried or exposed it, unless prescribed labelling or documentation requirements are met.", "depth": 2, "order": 61, "parentSection": "Part 6 — Obligatory provisions and offences", "status": "in_force", "crossReferences": ["s 169"]},
            {"sectionId": "s 173B", "title": "Consumption of liquor in certain public places prohibited", "content": "A person must not consume liquor in a public place that is a road, land owned by or under the control of a local government (other than certain conservation areas), or relevant State land prescribed under a regulation, or in a doorway, entrance or vestibule giving access to premises from such a public place. Maximum penalty — 1 penalty unit. Exceptions: consumption authorised under a licence or permit, or in a designated public place (a local government may designate public places where liquor may be consumed under section 173C).", "depth": 2, "order": 70, "parentSection": "Part 6 — Obligatory provisions and offences", "status": "in_force", "crossReferences": ["Liquor Regulation 2002 r 43"]},
            {"sectionId": "s 173EG", "title": "Licence conditions about regulated premises", "content": "The conditions that may be imposed on a licence include a condition declaring the licensed premises to be regulated premises for the ID-scanning division (Part 6AA), even for a licence of an exempt class. The police commissioner may recommend imposing such a condition and the commissioner must have regard to the recommendation. A licence condition for regulated premises may state a period to be the premises' regulated hours.", "depth": 2, "order": 80, "parentSection": "Part 6AA — ID scanning", "status": "in_force", "crossReferences": ["s 173EH", "s 173EHAAA"]},
            {"sectionId": "s 173EH", "title": "ID scanning obligations of staff members for regulated premises", "content": "During the regulated hours for regulated premises, the licensee must ensure the ID scanning entry requirements are complied with for all patron entries, and a staff member responsible for controlling an entry must ensure they are complied with for each patron the staff member allows in. Maximum penalty — 10 penalty units each. The obligations do not apply where the licensee is not authorised to sell or supply liquor after midnight, or (Monday–Thursday, other than before a public holiday) where the premises are not open after 1a.m. — unless a licence condition requires compliance regardless.", "depth": 2, "order": 81, "parentSection": "Part 6AA — ID scanning", "status": "in_force", "crossReferences": ["s 173EG", "s 173EHAAA"]},
            {"sectionId": "s 173EHAAA", "title": "ID scanning entry requirements for entry to regulated premises", "content": "The ID scanning entry requirements are that a patron must not be allowed to enter regulated premises unless the patron produces a photo ID, a staff member scans it using an approved ID scanner linked to an approved ID scanning system, and the scan indicates the patron is not subject to a banning order for the premises. On system failure, the photo ID must instead be checked against a current list of banned persons, with notice of the failure to the commissioner and police commissioner within 48 hours. Exemptions include residents, exempt minors, persons attending a function, and diners in a part of the premises ordinarily set aside for dining.", "depth": 2, "order": 82, "parentSection": "Part 6AA — ID scanning", "status": "in_force", "crossReferences": ["s 173EH"]},
            {"sectionId": "s 173NA", "title": "Purposes of pt 6AB", "content": "The purposes of Part 6AB (Safe night precincts) are to, in an area, minimise harm and the potential for harm from the abuse and misuse of alcohol and drugs and associated violence, and minimise alcohol and drug-related disturbances or public disorder. To achieve this, the part provides for areas to be prescribed as safe night precincts and for local boards and consultative committees to be established so licensees, the State and local governments, the police service and community organisations can collaborate.", "depth": 2, "order": 90, "parentSection": "Part 6AB — Safe night precincts", "status": "in_force", "crossReferences": ["s 173NC"]},
            {"sectionId": "s 173NC", "title": "Safe night precincts and local boards", "content": "A regulation may prescribe an area that has a concentration of licensed premises to be a safe night precinct, and may prescribe an incorporated association to be the local board for a safe night precinct. In recommending the regulation, the Minister must be satisfied it is necessary to achieve the purposes of the part. The prescribed precincts (15 across Queensland, including the Brisbane CBD and Fortitude Valley precincts) are set out in the Liquor Regulation 2002.", "depth": 2, "order": 91, "parentSection": "Part 6AB — Safe night precincts", "status": "in_force", "crossReferences": ["s 173NA", "Liquor Regulation 2002 r 3B", "s 86"]},
            {"sectionId": "s 235", "title": "Regulation-making power", "content": "The Governor in Council may make regulations under this Act, including with respect to application requirements, obligations of licensees and permittees, fees, consumption or possession of liquor in a public place, encouraging responsible practices in the service, supply and promotion of liquor, and the limits for noise coming from licensed premises. A regulation may create offences with a maximum penalty of 40 penalty units. The Liquor Regulation 2002 is made under this power.", "depth": 2, "order": 100, "parentSection": "Part 10 — Miscellaneous provisions", "status": "in_force", "crossReferences": ["Liquor Regulation 2002 r 40"]},
        ],
    },
    {
        "id": "qld/reg-2002-212",
        "jurisdiction": "QLD",
        "type": "regulation",
        "title": "Liquor Regulation 2002 (Qld)",
        "shortTitle": "Liquor Regulation 2002",
        "year": 2002,
        "number": "SL No. 212 of 2002",
        "administeredBy": "Office of Liquor and Gaming Regulation, Department of Justice",
        "legislationUrl": "https://www.legislation.qld.gov.au/view/whole/html/inforce/current/sl-2002-0212",
        "relatedDocs": ["qld/act-1992-021"],
        "sections": [
            {"sectionId": "r 3B", "title": "Safe night precincts — Act, s 173NC(1)", "content": "Prescribes 15 safe night precincts for section 173NC(1) of the Liquor Act 1992, each defined by a map in a schedule: Airlie Beach CBD (sch 2), Brisbane CBD (sch 3), Broadbeach CBD (sch 4), Bundaberg CBD (sch 5), Cairns CBD (sch 6), Fortitude Valley (sch 7), Gladstone CBD (sch 8), Inner West Brisbane (sch 9), Ipswich CBD (sch 10), Mackay CBD (sch 11), Rockhampton CBD (sch 12), Sunshine Coast (Maroochydore, Mooloolaba and Caloundra — sch 13), Surfers Paradise CBD (sch 14), Toowoomba CBD (sch 15), and Townsville CBD (sch 16). Boundary rules address road casements, footpaths, waterways and public structures. Three of the precincts fall within Brisbane: the Brisbane CBD, Fortitude Valley and Inner West Brisbane precincts.", "depth": 2, "order": 0, "parentSection": "Part 1A — Safe night precincts and identified organisations", "status": "in_force", "crossReferences": ["Liquor Act 1992 s 173NC"]},
            {"sectionId": "r 3F", "title": "Exempt class — Act, s 173EE", "content": "For the ID-scanning provisions (Part 6AA of the Act), prescribes the exempt classes of licence: a commercial special facility licence whose principal activity is a casino or a convention centre; a subsidiary on-premises licence (meals); a subsidiary on-premises licence whose principal activity is the provision of accommodation; and a community club licence.", "depth": 2, "order": 1, "parentSection": "Part 1A — Safe night precincts and identified organisations", "status": "in_force", "crossReferences": ["Liquor Act 1992 s 173EH"]},
            {"sectionId": "r 3FA", "title": "Prescribed conditions of licence for regulated premises — Act, s 58A", "content": "Prescribes licence conditions for regulated premises: the licensee must keep approved ID scanning equipment physically secure and protected from unauthorised access; must notify the approved operator of incidents affecting equipment integrity, security or performance; must have equipment serviced only through the approved operator; must prepare, implement and keep up to date a privacy management plan stating how the licensee will comply with the Privacy Act 1988 (Cwlth) for personal information recorded by an approved ID scanner; and must consider patron privacy complaints and notify the commissioner of them within 14 days.", "depth": 2, "order": 2, "parentSection": "Part 1A — Safe night precincts and identified organisations", "status": "in_force", "crossReferences": ["Liquor Act 1992 s 173EHAAA"]},
            {"sectionId": "r 27A", "title": "Drinking water to be available", "content": "A licensee holding a commercial hotel licence, community club licence, bar licence, nightclub licence, commercial public event permit or artisan producer licence (or certain other licences with a relevant extended trading hours approval, or a casino licence) must ensure clean and potable drinking water is available to each patron free of charge, at all times liquor is sold, by means other than a water tap located in a toilet facility. Maximum penalty — 40 penalty units. Other licensees must make drinking water available free of charge or at a reasonable cost.", "depth": 2, "order": 10, "parentSection": "Part 6 — Miscellaneous provisions about licences", "status": "in_force", "crossReferences": []},
            {"sectionId": "r 36B", "title": "Risk criterion — extended or authorised trading hours", "content": "Sets the risk-based licence fee component for premises with extended or authorised trading hours. The fee scales with how late the premises trade: from 1,107–1,471 fee units for early-morning (7–9a.m.) extensions up to 8,290–11,030 fee units for trading to 3a.m. and 11,030–14,730 fee units for trading between 3a.m. and 5a.m. — later trading attracts a materially higher regulatory risk loading.", "depth": 2, "order": 20, "parentSection": "Part 7A — Fees", "status": "in_force", "crossReferences": ["Liquor Act 1992 s 86"]},
            {"sectionId": "r 37C", "title": "Number of crowd controllers — Act, s 142AG", "content": "Prescribes the minimum number of crowd controllers for premises: 1 for up to 100 patrons, 2 for 101–200, 3 for 201–300, 4 for 301–400, 5 for 401–500, and 5 plus at least 1 additional crowd controller for each additional 250 patrons (or part thereof) above 500.", "depth": 2, "order": 30, "parentSection": "Part 8A — Provisions about conditions", "status": "in_force", "crossReferences": ["r 37D", "r 37E"]},
            {"sectionId": "r 37D", "title": "Minimum requirements for closed-circuit television equipment — Act, s 142AH(c)(i)", "content": "CCTV equipment required under the Act must clearly record, at each patron entrance and exit, all patrons entering or leaving and their interactions with crowd controllers or staff; must timestamp recordings; must be able to store each recording for at least 28 days on the equipment (and at least 1 year on the equipment or a related storage device); and must be able to produce digital copies of stored recordings.", "depth": 2, "order": 31, "parentSection": "Part 8A — Provisions about conditions", "status": "in_force", "crossReferences": ["r 37C", "r 37E"]},
            {"sectionId": "r 37E", "title": "Information for incident register — Act, s 142AI", "content": "Prescribes the information to be recorded in a licensed venue's incident register: date and time of the incident, where at the premises it happened, a description of each person involved (and name if known), details of the incident including whether a patron was removed, details of injuries sustained, and details of action taken by crowd controllers or staff in response.", "depth": 2, "order": 32, "parentSection": "Part 8A — Provisions about conditions", "status": "in_force", "crossReferences": ["r 37C", "r 37D"]},
            {"sectionId": "r 38", "title": "Approved training course — Act, s 4, definition approved training course", "content": "Prescribes the responsible service of alcohol (RSA) training course for the Act: the course called 'Provide responsible service of alcohol' that is a unit of competency or module of a VET course under the National Vocational Education and Training Regulator Act 2011 (Cwlth), for which a VET statement of attainment is given.", "depth": 2, "order": 40, "parentSection": "Part 9 — Miscellaneous", "status": "in_force", "crossReferences": ["Liquor Act 1992 s 4"]},
            {"sectionId": "r 40", "title": "Prescription of limits for noise that if exceeded constitute unreasonable noise", "content": "Prescribes the measurable noise limits for the definition of 'unreasonable noise' in section 4 of the Act: (a) between 6a.m. and 10p.m. — the adjusted maximum sound pressure level LA10, plus adjustments for tonal and impulse components, must not exceed the background level LA90 by more than 10dB(A); (b) between 10p.m. and 6a.m. — the sound pressure level LOCT10, in a full octave band with centre frequencies from 63Hz to 2,000Hz, must not exceed the background level LOCT90 by more than 8dB in any octave band. These are the operative acoustic criteria for noise from licensed premises in Queensland.", "depth": 2, "order": 41, "parentSection": "Part 9 — Miscellaneous", "status": "in_force", "crossReferences": ["Liquor Act 1992 s 4", "Liquor Act 1992 s 235"]},
            {"sectionId": "r 41", "title": "Unacceptable practices and promotions — Act, s 142ZZ(2)(g)", "content": "Prescribes, as an additional unacceptable practice for section 142ZZ(2)(g) of the Act, serving or supplying liquor to a patron while holding the patron's financial institution access card or other property pending payment, in a way that discourages the patron from monitoring or controlling their purchase of liquor.", "depth": 2, "order": 42, "parentSection": "Part 9 — Miscellaneous", "status": "in_force", "crossReferences": ["Liquor Act 1992 s 142ZZ"]},
            {"sectionId": "r 41B", "title": "Rapid intoxication drinks — Act, s 155AG(b)", "content": "Prescribes the drinks that are rapid intoxication drinks for the Act's restricted-period sale prohibition: shots, shooters, bombs, blasters, test tubes and jelly shots (and similar drinks served in small containers allowing rapid consumption); drinks prepared on premises containing more than 45ml of spirits or liqueur; and pre-mixed alcoholic drinks over 5% alcohol by volume or containing more than 2 standard drinks. Listed, regularly-priced cocktails not designed for rapid consumption are excluded.", "depth": 2, "order": 43, "parentSection": "Part 9 — Miscellaneous", "status": "in_force", "crossReferences": ["Liquor Act 1992 s 155AI"]},
            {"sectionId": "r 43", "title": "Prescribed public places where consumption of liquor is prohibited — Act, s 173B(1)(a)(iii)", "content": "Prescribes South Bank Parklands (the South Bank corporation area, other than certain leased or freehold land) as a public place where consumption of liquor is prohibited under section 173B(1)(a)(iii) of the Act.", "depth": 2, "order": 44, "parentSection": "Part 9 — Miscellaneous", "status": "in_force", "crossReferences": ["Liquor Act 1992 s 173B"]},
        ],
    },
]


def main():
    parser = argparse.ArgumentParser(description="Seed QLD liquor legislation into PACT")
    parser.add_argument("--base-url", default=os.environ.get("SOURCE_BASE_URL", DEFAULT_BASE))
    parser.add_argument("--admin-key", default=os.environ.get("ADMIN_SECRET", ""))
    args = parser.parse_args()

    base = args.base_url.rstrip("/")
    admin_key = args.admin_key

    if not admin_key:
        print("ERROR: No admin key provided. Set ADMIN_SECRET env var or use --admin-key")
        sys.exit(1)

    print(f"Seeding {len(LIQUOR_DOCS)} QLD liquor legislation documents to {base}")
    print(f"Total sections: {sum(len(d.get('sections', [])) for d in LIQUOR_DOCS)}")
    print()

    url = f"{base}/api/axiom/legislation/ingest"
    headers = {
        "Content-Type": "application/json",
        "X-Admin-Key": admin_key,
    }

    resp = requests.post(url, json={"documents": LIQUOR_DOCS}, headers=headers, timeout=60)

    if resp.status_code != 200:
        print(f"FAILED: HTTP {resp.status_code}")
        print(resp.text[:500])
        sys.exit(1)

    data = resp.json()
    print(f"SUCCESS: Ingested {data['ingested']} documents")
    for doc in data.get("documents", []):
        print(f"  {doc['id']:24s}  {doc['sectionsInserted']:3d} sections  {doc['title']}")

    print()
    print(f"Total sections ingested: {sum(d['sectionsInserted'] for d in data.get('documents', []))}")
    print()
    print("Verify:")
    print(f"  GET {base}/api/axiom/legislation/search?q=Liquor%20Act%201992")
    print(f"  GET {base}/api/axiom/legislation/qld%2Fact-1992-021?section=s%20169&format=text")
    print(f"  GET {base}/api/axiom/legislation/qld%2Freg-2002-212?section=r%2040&format=text")


if __name__ == "__main__":
    main()
